const SentencesData = {
  VORSTELLUNG: {
    name: 'Vorstellung – Herkunft, Arbeit, Interessen',
    sentences: [
      { italian: 'Vengo da Vienna, ho 47 anni e lavoro da molti anni nel settore IT.', german: 'Ich komme aus Wien, bin 47 Jahre alt und arbeite seit vielen Jahren im IT-Bereich.' },
      { italian: 'Sono nato e cresciuto a Vienna e oggi vivo ancora nei dintorni della città.', german: 'Ich bin in Wien geboren und aufgewachsen und lebe heute noch in der Nähe der Stadt.' },
      { italian: 'Lavoro per una grande azienda IT e mi occupo di progetti tecnologici internazionali.', german: 'Ich arbeite für ein großes IT-Unternehmen und beschäftige mich mit internationalen Technologieprojekten.' },
      { italian: 'Il mio lavoro è molto impegnativo, ma mi piace perché è stimolante e vario.', german: 'Meine Arbeit ist sehr anspruchsvoll, aber sie gefällt mir, weil sie abwechslungsreich und spannend ist.' },
      { italian: 'Oltre al lavoro, la mia famiglia è la cosa più importante nella mia vita.', german: 'Neben der Arbeit ist meine Familie das Wichtigste in meinem Leben.' },
      { italian: 'Sono una persona curiosa e mi piace imparare sempre cose nuove.', german: 'Ich bin ein neugieriger Mensch und lerne gerne ständig Neues dazu.' },
      { italian: 'Sono un grande fan dell\'Italia e mi sento molto legato alla cultura italiana.', german: 'Ich bin ein großer Italien-Fan und fühle mich der italienischen Kultur sehr verbunden.' },
      { italian: 'Amo la mentalità italiana, soprattutto il modo di vivere e di godersi la vita.', german: 'Ich liebe die italienische Mentalität, vor allem die Art zu leben und das Leben zu genießen.' },
      { italian: 'La cucina italiana è una delle mie grandi passioni.', german: 'Die italienische Küche ist eine meiner großen Leidenschaften.' },
      { italian: 'Mi piace cucinare a casa e provare nuove ricette, soprattutto italiane.', german: 'Ich koche gerne zu Hause und probiere neue Rezepte aus, besonders italienische.' },
      { italian: 'Nel tempo libero mi rilasso cucinando per la mia famiglia e per gli amici.', german: 'In meiner Freizeit entspanne ich mich beim Kochen für meine Familie und Freunde.' },
      { italian: 'Viaggiare è un\'altra mia grande passione.', german: 'Reisen ist eine weitere große Leidenschaft von mir.' },
      { italian: 'Amo scoprire nuovi paesi, culture diverse e persone interessanti.', german: 'Ich liebe es, neue Länder, andere Kulturen und interessante Menschen kennenzulernen.' },
      { italian: 'Ho già viaggiato molto, ma c\'è ancora tantissimo che voglio vedere.', german: 'Ich bin schon viel gereist, aber es gibt noch sehr viel, das ich sehen möchte.' },
      { italian: 'Per me viaggiare significa uscire dalla routine e aprire la mente.', german: 'Für mich bedeutet Reisen, aus der Routine auszubrechen und den Horizont zu erweitern.' },
      { italian: 'Mi piace sia viaggiare in grandi città sia in posti tranquilli nella natura.', german: 'Ich reise gerne sowohl in große Städte als auch in ruhige Orte in der Natur.' },
      { italian: 'Sono una persona aperta e mi piace fare nuove conoscenze.', german: 'Ich bin ein offener Mensch und lerne gern neue Leute kennen.' },
      { italian: 'Parlo tedesco e inglese e ho iniziato da poco a studiare l\'italiano.', german: 'Ich spreche Deutsch und Englisch und habe erst vor Kurzem begonnen, Italienisch zu lernen.' },
      { italian: 'Imparare una nuova lingua è una sfida, ma anche una grande soddisfazione.', german: 'Eine neue Sprache zu lernen ist eine Herausforderung, aber auch sehr erfüllend.' },
      { italian: 'Cerco sempre di migliorarmi, sia nel lavoro sia nella vita privata.', german: 'Ich versuche mich immer weiterzuentwickeln, beruflich wie privat.' },
      { italian: 'La mia passione per le auto italiane parte dalla mia gioventù.', german: 'Meine Leidenschaft für italienische Autos reicht bis in meine Jugend.' },
      { italian: 'Mi interessa il design, la storia e la cultura dell\'Italia.', german: 'Mich interessieren Design, Geschichte und Kultur Italiens.' }
    ]
  },
  AUTO: {
    name: 'Auto, Passione, Formula 1, Marchi Italiani',
    sentences: [
      { italian: 'Le auto sono una mia grande passione da quando ero giovane.', german: 'Autos sind seit meiner Jugend eine große Leidenschaft von mir.' },
      { italian: 'Mi interessano non solo le auto moderne, ma anche quelle storiche.', german: 'Mich interessieren nicht nur moderne Autos, sondern auch historische.' },
      { italian: 'Amo soprattutto le auto italiane per il loro design e il loro carattere.', german: 'Ich liebe vor allem italienische Autos wegen ihres Designs und Charakters.' },
      { italian: 'Le auto italiane hanno, secondo me, un\'anima speciale.', german: 'Italienische Autos haben meiner Meinung nach eine besondere Seele.' },
      { italian: 'Sono un grande appassionato di Formula 1.', german: 'Ich bin ein großer Formel-1-Fan.' },
      { italian: 'Seguo la Formula 1 da molti anni e non mi perdo quasi nessuna gara.', german: 'Ich verfolge die Formel 1 seit vielen Jahren und verpasse kaum ein Rennen.' },
      { italian: 'Naturalmente tifo per la Ferrari.', german: 'Natürlich halte ich zu Ferrari.' },
      { italian: 'Ferrari per me rappresenta passione, storia e tradizione.', german: 'Ferrari steht für mich für Leidenschaft, Geschichte und Tradition.' },
      { italian: 'Mi piace molto anche il marchio Alfa Romeo.', german: 'Ich mag auch die Marke Alfa Romeo sehr.' },
      { italian: 'Alfa Romeo unisce sportività ed eleganza in un modo unico.', german: 'Alfa Romeo verbindet Sportlichkeit und Eleganz auf einzigartige Weise.' },
      { italian: 'Sono anche un grande fan di Fiat.', german: 'Ich bin auch ein großer Fan von Fiat.' },
      { italian: 'Fiat ha una storia incredibile ed è molto legata all\'Italia.', german: 'Fiat hat eine unglaubliche Geschichte und ist stark mit Italien verbunden.' },
      { italian: 'Mi affascina il modo in cui le auto italiane combinano emozione e tecnica.', german: 'Mich fasziniert, wie italienische Autos Emotion und Technik verbinden.' },
      { italian: 'Per me guidare non è solo spostarsi, ma vivere un\'esperienza.', german: 'Für mich ist Autofahren nicht nur Fortbewegung, sondern ein Erlebnis.' },
      { italian: 'Mi piace parlare di auto e scambiare opinioni con altri appassionati.', german: 'Ich spreche gern über Autos und tausche mich mit anderen Fans aus.' },
      { italian: 'Seguo con interesse le novità del mondo automobilistico.', german: 'Ich verfolge die Neuigkeiten aus der Automobilwelt mit Interesse.' },
      { italian: 'Anche il suono del motore è molto importante per me.', german: 'Auch der Klang des Motors ist mir sehr wichtig.' },
      { italian: 'Quando vedo una bella auto italiana, mi fermo sempre a guardarla.', german: 'Wenn ich ein schönes italienisches Auto sehe, bleibe ich immer stehen.' },
      { italian: 'Le auto raccontano molto della cultura di un paese.', german: 'Autos erzählen viel über die Kultur eines Landes.' },
      { italian: 'Per me l\'Italia è uno dei paesi più importanti nella storia dell\'automobile.', german: 'Für mich ist Italien eines der wichtigsten Länder in der Automobilgeschichte.' },
      { italian: 'Le curve e il design delle auto italiane sono inimitabili.', german: 'Die Kurven und das Design italienischer Autos sind unvergleichlich.' },
      { italian: 'Visito regolarmente musei automobilistici in Italia.', german: 'Ich besuche regelmäßig Automobilmuseen in Italien.' },
      { italian: 'La passione per le auto mi aiuta a rilassarmi dopo il lavoro.', german: 'Die Leidenschaft für Autos hilft mir, mich nach der Arbeit zu entspannen.' },
      { italian: 'Qualche volta leggo riviste di auto e guardo video su YouTube.', german: 'Manchmal lese ich Autozeitschriften und schaue Videos auf YouTube.' },
      { italian: 'I miei figli condividono un po\' della mia passione per le auto.', german: 'Meine Kinder teilen etwas meine Leidenschaft für Autos.' },
      { italian: 'Mi piacerebbe possedere una Alfa Romeo 1750 Sprint Veloce.', german: 'Ich würde gerne einen Alfa Romeo 1750 Sprint Veloce besitzen.' },
      { italian: 'Il rumore dell\'accelerazione di una Ferrari è incomparabile.', german: 'Das Geräusch der Beschleunigung eines Ferrari ist unvergleichlich.' },
      { italian: 'L\'artigianalità italiana nella costruzione di auto è molto bella.', german: 'Die italienische Handwerkskunst beim Autobau ist sehr schön.' },
      { italian: 'Penso che le auto siano parte della storia d\'Italia.', german: 'Ich denke, dass Autos Teil der Italienischen Geschichte sind.' }
    ]
  },
  FAMIGLIA: {
    name: 'Familie, Casa, Figli, Cane, Sorella',
    sentences: [
      { italian: 'Vivo con mia moglie e i nostri tre figli vicino a Vienna.', german: 'Ich lebe mit meiner Frau und unseren drei Kindern in der Nähe von Wien.' },
      { italian: 'La famiglia per me è sempre al primo posto.', german: 'Die Familie steht für mich immer an erster Stelle.' },
      { italian: 'Abbiamo tre figli che hanno 17, 18 e 19 anni.', german: 'Wir haben drei Kinder, die 17, 18 und 19 Jahre alt sind.' },
      { italian: 'I nostri figli stanno crescendo molto velocemente.', german: 'Unsere Kinder werden sehr schnell erwachsen.' },
      { italian: 'Viviamo in una casa con giardino.', german: 'Wir leben in einem Haus mit Garten.' },
      { italian: 'Il giardino è un posto importante per rilassarci e passare tempo insieme.', german: 'Der Garten ist ein wichtiger Ort zum Entspannen und Zusammensein.' },
      { italian: 'Abbiamo anche un cane che fa parte della nostra famiglia.', german: 'Wir haben auch einen Hund, der zur Familie gehört.' },
      { italian: 'Il cane porta molta gioia e movimento nella nostra vita quotidiana.', german: 'Der Hund bringt viel Freude und Bewegung in unseren Alltag.' },
      { italian: 'Mi piace passare il tempo libero con la mia famiglia.', german: 'Ich verbringe meine Freizeit gern mit meiner Familie.' },
      { italian: 'Cerchiamo di mangiare spesso insieme, soprattutto la sera.', german: 'Wir versuchen oft gemeinsam zu essen, besonders abends.' },
      { italian: 'Viviamo vicino a Vienna, ma in una zona tranquilla.', german: 'Wir leben nahe Wien, aber in einer ruhigen Gegend.' },
      { italian: 'Abbiamo la tranquillità, ma anche la città non è lontana.', german: 'Wir haben Ruhe, aber die Stadt ist nicht weit entfernt.' },
      { italian: 'Mia moglie ed io condividiamo molti interessi.', german: 'Meine Frau und ich teilen viele Interessen.' },
      { italian: 'Cerchiamo di sostenere i nostri figli in ogni fase della loro vita.', german: 'Wir versuchen, unsere Kinder in jeder Lebensphase zu unterstützen.' },
      { italian: 'Ho anche una sorella.', german: 'Ich habe auch eine Schwester.' },
      { italian: 'Mia sorella è cinque anni più giovane di me.', german: 'Meine Schwester ist fünf Jahre jünger als ich.' },
      { italian: 'Andiamo molto d\'accordo e abbiamo un buon rapporto.', german: 'Wir verstehen uns sehr gut und haben ein gutes Verhältnis.' },
      { italian: 'La famiglia è per me una fonte di forza e stabilità.', german: 'Die Familie ist für mich eine Quelle von Stärke und Stabilität.' },
      { italian: 'Mi piace tornare a casa dopo una giornata intensa di lavoro.', german: 'Ich komme nach einem anstrengenden Arbeitstag gern nach Hause.' },
      { italian: 'Casa e famiglia sono il mio punto di equilibrio.', german: 'Haus und Familie sind mein Ausgleichspunkt.' },
      { italian: 'I nostri figli hanno diversi hobby e interessi.', german: 'Unsere Kinder haben verschiedene Hobbys und Interessen.' },
      { italian: 'Mia moglie è un\'insegnante molto dedicata.', german: 'Meine Frau ist eine sehr engagierte Lehrerin.' },
      { italian: 'Nel fine settimana facciamo spesso gite insieme.', german: 'Am Wochenende machen wir oft Ausflüge zusammen.' },
      { italian: 'Il nostro cane è un labrador retriever.', german: 'Unser Hund ist ein Labrador Retriever.' },
      { italian: 'La mia sorella vive anche vicino a Vienna.', german: 'Meine Schwester lebt auch in der Nähe von Wien.' }
    ]
  },
  ITALIANO: {
    name: 'Italiano, Lingua, Komunikation',
    sentences: [
      { italian: 'Ho iniziato a imparare l\'italiano solo da poco.', german: 'Ich habe erst vor Kurzem begonnen, Italienisch zu lernen.' },
      { italian: 'L\'italiano è una lingua bellissima, ma non sempre facile.', german: 'Italienisch ist eine wunderschöne Sprache, aber nicht immer einfach.' },
      { italian: 'Sto cercando di migliorare un po\' ogni giorno.', german: 'Ich versuche, mich jeden Tag ein bisschen zu verbessern.' },
      { italian: 'Posso provare a parlare in italiano?', german: 'Darf ich versuchen, Italienisch zu sprechen?' },
      { italian: 'Mi scusi, sto ancora imparando.', german: 'Entschuldigung, ich lerne noch.' },
      { italian: 'Può parlare un po\' più lentamente, per favore?', german: 'Könnten Sie bitte etwas langsamer sprechen?' },
      { italian: 'Capisco abbastanza bene, ma parlare è ancora difficile per me.', german: 'Ich verstehe ziemlich gut, aber Sprechen ist noch schwierig für mich.' },
      { italian: 'Se non capisco qualcosa, posso chiedere?', german: 'Wenn ich etwas nicht verstehe, darf ich fragen?' },
      { italian: 'A volte capisco le parole, ma non tutta la frase.', german: 'Manchmal verstehe ich die Wörter, aber nicht den ganzen Satz.' },
      { italian: 'Mi scusi se faccio degli errori.', german: 'Entschuldigung, wenn ich Fehler mache.' },
      { italian: 'Sto cercando di fare pratica il più possibile.', german: 'Ich versuche, so viel wie möglich zu üben.' },
      { italian: 'Può ripetere, per favore?', german: 'Können Sie das bitte wiederholen?' },
      { italian: 'Può spiegarmelo in un altro modo?', german: 'Könnten Sie es mir anders erklären?' },
      { italian: 'Parlo un po\' di italiano, ma non sono ancora sicuro.', german: 'Ich spreche ein bisschen Italienisch, bin aber noch nicht sicher.' },
      { italian: 'Preferisco parlare lentamente e con frasi semplici.', german: 'Ich spreche lieber langsam und mit einfachen Sätzen.' },
      { italian: 'Capisco meglio se si parla piano.', german: 'Ich verstehe besser, wenn man langsam spricht.' },
      { italian: 'Grazie per la pazienza.', german: 'Danke für Ihre Geduld.' },
      { italian: 'Imparare l\'italiano è importante per me.', german: 'Italienisch zu lernen ist mir wichtig.' },
      { italian: 'Mi piace molto ascoltare l\'italiano parlato.', german: 'Ich höre sehr gerne gesprochenes Italienisch.' },
      { italian: 'Spero di parlare sempre meglio con il tempo.', german: 'Ich hoffe, mit der Zeit immer besser zu sprechen.' }
    ]
  },
  SMALLTALK: {
    name: 'Small Talk',
    sentences: [
      { italian: 'Come va oggi?', german: 'Wie geht es Ihnen heute?' },
      { italian: 'Tutto bene, grazie, e lei?', german: 'Alles gut, danke, und Ihnen?' },
      { italian: 'È la mia prima volta qui e mi piace molto questo posto.', german: 'Ich bin zum ersten Mal hier und mir gefällt dieser Ort sehr.' },
      { italian: 'Il tempo oggi è davvero bello.', german: 'Das Wetter ist heute wirklich schön.' },
      { italian: 'Mi piace molto l\'atmosfera di questa città.', german: 'Mir gefällt die Atmosphäre dieser Stadt sehr.' },
      { italian: 'Da quanto tempo vive qui?', german: 'Wie lange leben Sie schon hier?' },
      { italian: 'È sempre così tranquillo qui?', german: 'Ist es hier immer so ruhig?' },
      { italian: 'Mi piace molto come vivono le persone qui.', german: 'Mir gefällt sehr, wie die Menschen hier leben.' },
      { italian: 'Vengo dall\'Austria, precisamente da Vienna.', german: 'Ich komme aus Österreich, genauer gesagt aus Wien.' },
      { italian: 'Sono qui per lavoro e anche un po\' per piacere.', german: 'Ich bin beruflich hier, aber auch ein bisschen privat.' },
      { italian: 'Mi piace osservare la vita quotidiana nei posti che visito.', german: 'Ich beobachte gern den Alltag an Orten, die ich besuche.' },
      { italian: 'L\'Italia mi fa sentire sempre a mio agio.', german: 'Italien gibt mir immer ein gutes Gefühl.' },
      { italian: 'È un posto molto diverso da dove vivo io.', german: 'Es ist ein ganz anderer Ort als dort, wo ich lebe.' },
      { italian: 'Mi piace fare due chiacchiere e conoscere nuove persone.', german: 'Ich unterhalte mich gern und lerne neue Menschen kennen.' },
      { italian: 'È una zona molto bella per passeggiare.', german: 'Das ist eine sehr schöne Gegend zum Spazierengehen.' },
      { italian: 'C\'è qualcosa che mi consiglia di vedere qui?', german: 'Gibt es etwas, das Sie mir empfehlen würden?' },
      { italian: 'Mi piace scoprire posti non troppo turistici.', german: 'Ich entdecke gern weniger touristische Orte.' },
      { italian: 'Il caffè qui è davvero ottimo.', german: 'Der Kaffee hier ist wirklich ausgezeichnet.' },
      { italian: 'Si mangia molto bene da queste parti.', german: 'In dieser Gegend isst man sehr gut.' },
      { italian: 'È sempre un piacere tornare in Italia.', german: 'Es ist immer eine Freude, nach Italien zurückzukommen.' },
      { italian: 'Quanto tempo rimane qui?', german: 'Wie lange bleiben Sie hier?' },
      { italian: 'Ha già visitato altri posti in Italia?', german: 'Haben Sie bereits andere Orte in Italien besucht?' },
      { italian: 'Le piace la cucina italiana?', german: 'Mag die italienische Küche?' },
      { italian: 'Che cosa vi piace fare nel tempo libero?', german: 'Was machen Sie gerne in der Freizeit?' },
      { italian: 'Della bellezza di questa regione sono veramente affascinato.', german: 'Ich bin von der Schönheit dieser Region wirklich fasziniert.' },
      { italian: 'Le persone qui sono molto cordiali e amichevoli.', german: 'Die Menschen hier sind sehr herzlich und freundlich.' },
      { italian: 'Mi piacerebbe tornare qui ancora una volta.', german: 'Ich würde gerne noch einmal hierher kommen.' },
      { italian: 'Avete qualche raccomandazione per mangiare?', german: 'Haben Sie Empfehlungen zum Essen?' },
      { italian: 'La vista da qui è spettacolare.', german: 'Die Aussicht von hier ist spektakulär.' },
      { italian: 'Mi piace fare fotografie di questi posti.', german: 'Ich mache gerne Fotos von diesen Orten.' },
      { italian: 'Questo è veramente un luogo incantevole.', german: 'Das ist wirklich ein bezaubernder Ort.' },
      { italian: 'Non vedo l\'ora di esplorare di più.', german: 'Ich bin schon gespannt auf weitere Entdeckungen.' }
    ]
  },
  RISTORANTE: {
    name: 'Ristorante',
    sentences: [
      { italian: 'Buonasera, abbiamo un tavolo per due, per favore?', german: 'Guten Abend, haben Sie einen Tisch für zwei?' },
      { italian: 'Potremmo sederci fuori, se possibile?', german: 'Könnten wir draußen sitzen, wenn möglich?' },
      { italian: 'Possiamo vedere il menu, per favore?', german: 'Könnten wir bitte die Speisekarte sehen?' },
      { italian: 'Che cosa ci consiglia oggi?', german: 'Was empfehlen Sie uns heute?' },
      { italian: 'C\'è qualche piatto tipico della zona?', german: 'Gibt es ein typisches Gericht aus der Region?' },
      { italian: 'Preferisco qualcosa di semplice, ma tradizionale.', german: 'Ich bevorzuge etwas Einfaches, aber Traditionelles.' },
      { italian: 'Prenderei volentieri un piatto di pasta.', german: 'Ich würde gerne ein Pastagericht nehmen.' },
      { italian: 'Non mangio molto piccante.', german: 'Ich esse nicht sehr scharf.' },
      { italian: 'Potrei avere un po\' più di tempo per decidere?', german: 'Könnte ich noch etwas Zeit zum Entscheiden bekommen?' },
      { italian: 'Come è preparato questo piatto?', german: 'Wie wird dieses Gericht zubereitet?' },
      { italian: 'È possibile avere una porzione più piccola?', german: 'Ist eine kleinere Portion möglich?' },
      { italian: 'Tutto è stato davvero molto buono.', german: 'Alles war wirklich sehr gut.' },
      { italian: 'Complimenti allo chef, il cibo era eccellente.', german: 'Kompliment an den Koch, das Essen war hervorragend.' },
      { italian: 'Potremmo avere ancora un po\' d\'acqua, per favore?', german: 'Könnten wir bitte noch etwas Wasser bekommen?' },
      { italian: 'Prendiamo una bottiglia di vino della casa.', german: 'Wir nehmen eine Flasche Hauswein.' },
      { italian: 'Per me solo acqua, grazie.', german: 'Für mich nur Wasser, danke.' },
      { italian: 'Possiamo avere il conto, per favore?', german: 'Könnten wir bitte die Rechnung bekommen?' },
      { italian: 'È possibile pagare con carta?', german: 'Kann man mit Karte zahlen?' },
      { italian: 'Torneremo sicuramente, ci siamo trovati molto bene.', german: 'Wir kommen sicher wieder, es hat uns sehr gefallen.' },
      { italian: 'Grazie mille, è stata una bellissima esperienza.', german: 'Vielen Dank, es war eine sehr schöne Erfahrung.' }
    ]
  },
  VIAGGIO: {
    name: 'Viaggio / Hotel',
    sentences: [
      { italian: 'Buongiorno, ho una prenotazione a nome di…', german: 'Guten Morgen, ich habe eine Reservierung auf den Namen …' },
      { italian: 'Siamo arrivati oggi e restiamo per tre notti.', german: 'Wir sind heute angekommen und bleiben drei Nächte.' },
      { italian: 'È possibile fare il check-in adesso?', german: 'Ist ein Check-in jetzt möglich?' },
      { italian: 'A che ora è la colazione?', german: 'Um wie viel Uhr ist das Frühstück?' },
      { italian: 'La colazione è inclusa nel prezzo?', german: 'Ist das Frühstück im Preis inbegriffen?' },
      { italian: 'C\'è il Wi-Fi in hotel?', german: 'Gibt es WLAN im Hotel?' },
      { italian: 'La connessione Wi-Fi è gratuita?', german: 'Ist das WLAN kostenlos?' },
      { italian: 'Potrei avere informazioni sulla zona?', german: 'Könnte ich Informationen über die Umgebung bekommen?' },
      { italian: 'C\'è un buon ristorante vicino all\'hotel?', german: 'Gibt es ein gutes Restaurant in der Nähe des Hotels?' },
      { italian: 'Come posso arrivare al centro città?', german: 'Wie komme ich ins Stadtzentrum?' },
      { italian: 'È possibile lasciare i bagagli dopo il check-out?', german: 'Kann man das Gepäck nach dem Check-out noch dalassen?' },
      { italian: 'A che ora dobbiamo lasciare la camera?', german: 'Um wie viel Uhr müssen wir das Zimmer verlassen?' },
      { italian: 'La stanza è molto bella e confortevole.', german: 'Das Zimmer ist sehr schön und komfortabel.' },
      { italian: 'Se c\'è un problema, posso chiamare la reception?', german: 'Kann ich die Rezeption anrufen, wenn es ein Problem gibt?' },
      { italian: 'Potrei avere un asciugamano in più, per favore?', german: 'Könnte ich bitte ein zusätzliches Handtuch bekommen?' },
      { italian: 'L\'aria condizionata funziona bene.', german: 'Die Klimaanlage funktioniert gut.' },
      { italian: 'Possiamo prenotare un taxi tramite l\'hotel?', german: 'Können wir über das Hotel ein Taxi bestellen?' },
      { italian: 'Ci consiglia qualche attrazione nei dintorni?', german: 'Können Sie Sehenswürdigkeiten in der Nähe empfehlen?' },
      { italian: 'Il soggiorno è stato molto piacevole.', german: 'Der Aufenthalt war sehr angenehm.' },
      { italian: 'Grazie per l\'aiuto e per la gentilezza.', german: 'Vielen Dank für die Hilfe und Freundlichkeit.' },
      { italian: 'Vorremmo tornare ancora una volta.', german: 'Wir würden gerne noch einmal wiederkommen.' }
    ]
  }
};
