const VerbData = {
  ESSERE: {
    name: 'ESSERE (sein)',
    sentences: [
      { italian: 'Sono a casa.', german: 'Ich bin zu Hause.' },
      { italian: 'Sei pronto?', german: 'Bist du bereit?' },
      { italian: 'È tardi.', german: 'Es ist spät.' },
      { italian: 'Lei è stanca.', german: 'Sie ist müde.' },
      { italian: 'Siamo in ufficio.', german: 'Wir sind im Büro.' },
      { italian: 'Siete liberi stasera?', german: 'Seid ihr heute Abend frei?' },
      { italian: 'Sono felici.', german: 'Sie sind glücklich.' },
      { italian: 'Non sono sicuro.', german: 'Ich bin nicht sicher.' },
      { italian: 'È qui vicino?', german: 'Ist es hier in der Nähe?' },
      { italian: 'Siamo pronti a partire.', german: 'Wir sind startklar.' },
      { italian: 'Sono in ritardo per la riunione.', german: 'Ich bin zu spät für die Besprechung.' },
      { italian: 'Sei ancora al lavoro o torni?', german: 'Bist du noch bei der Arbeit, oder kommst du zurück?' },
      { italian: 'È d\'accordo con la proposta.', german: 'Er/Sie ist mit dem Vorschlag einverstanden.' },
      { italian: 'Siamo contenti del risultato.', german: 'Wir sind mit dem Ergebnis zufrieden.' },
      { italian: 'Siete davvero occupati oggi?', german: 'Seid ihr heute wirklich beschäftigt?' },
      { italian: 'Sono qui da mezz\'ora.', german: 'Ich bin seit einer halben Stunde hier.' },
      { italian: 'Non sono convinto di questa idea.', german: 'Ich bin von dieser Idee nicht überzeugt.' },
      { italian: 'È possibile che sia meglio così?', german: 'Ist es möglich, dass es so besser ist?' },
      { italian: 'Siamo abituati a lavorare da remoto.', german: 'Wir sind an Remote-Arbeit gewöhnt.' },
      { italian: 'Sono sempre gentili con i clienti.', german: 'Sie sind immer freundlich zu den Kunden.' },
      { italian: 'Sono stato a casa tutto il giorno.', german: 'Ich war den ganzen Tag zu Hause.' },
      { italian: 'Sei stato a scuola ieri?', german: 'Warst du gestern in der Schule?' },
      { italian: 'È stato facile.', german: 'Es war einfach.' },
      { italian: 'Lei è stata malata.', german: 'Sie war krank.' },
      { italian: 'Siamo stati in città.', german: 'Wir waren in der Stadt.' },
      { italian: 'Siete stati puntuali.', german: 'Ihr wart pünktlich.' },
      { italian: 'Sono stati felici.', german: 'Sie waren glücklich.' },
      { italian: 'Non sono stato al lavoro.', german: 'Ich war nicht bei der Arbeit.' },
      { italian: 'È stata una buona idea?', german: 'War es eine gute Idee?' },
      { italian: 'Siamo stati qui ieri sera.', german: 'Wir waren gestern Abend hier.' },
      { italian: 'Sono stato occupato tutta la mattina.', german: 'Ich war den ganzen Morgen beschäftigt.' },
      { italian: 'Sei stato d\'accordo con la decisione?', german: 'Warst du mit der Entscheidung einverstanden?' },
      { italian: 'È stato difficile trovare parcheggio.', german: 'Es war schwierig, einen Parkplatz zu finden.' },
      { italian: 'Lei è stata molto paziente con me.', german: 'Sie war sehr geduldig mit mir.' },
      { italian: 'Siamo stati soddisfatti del servizio.', german: 'Wir waren mit dem Service zufrieden.' },
      { italian: 'Siete stati in vacanza a luglio?', german: 'Wart ihr im Juli im Urlaub?' },
      { italian: 'Sono stati qui finché non ha smesso di piovere.', german: 'Sie waren hier, bis es aufgehört hat zu regnen.' },
      { italian: 'Non sono stato sicuro fino all\'ultimo.', german: 'Ich war bis zuletzt nicht sicher.' },
      { italian: 'È stata davvero la scelta migliore?', german: 'War das wirklich die beste Wahl?' },
      { italian: 'Siamo stati molto contenti del risultato.', german: 'Wir waren sehr zufrieden mit dem Ergebnis.' }
    ]
  },

  AVERE: {
    name: 'AVERE (haben)',
    sentences: [
      { italian: 'Ho fame.', german: 'Ich habe Hunger.' },
      { italian: 'Hai tempo oggi?', german: 'Hast du heute Zeit?' },
      { italian: 'Ha freddo.', german: 'Ihm/Ihr ist kalt.' },
      { italian: 'Abbiamo una riunione alle tre.', german: 'Wir haben um drei eine Besprechung.' },
      { italian: 'Avete domande?', german: 'Habt ihr Fragen?' },
      { italian: 'Hanno due bambini.', german: 'Sie haben zwei Kinder.' },
      { italian: 'Non ho contanti.', german: 'Ich habe kein Bargeld.' },
      { italian: 'Hai un minuto?', german: 'Hast du eine Minute?' },
      { italian: 'Ha un cane molto calmo.', german: 'Er/Sie hat einen sehr ruhigen Hund.' },
      { italian: 'Abbiamo tempo dopo cena.', german: 'Wir haben nach dem Abendessen Zeit.' },
      { italian: 'Ho bisogno di aiuto con il computer.', german: 'Ich brauche Hilfe mit dem Computer.' },
      { italian: 'Hai ancora voglia di uscire?', german: 'Hast du noch Lust auszugehen?' },
      { italian: 'Ha spesso mal di testa.', german: 'Er/Sie hat oft Kopfschmerzen.' },
      { italian: 'Abbiamo abbastanza soldi per il viaggio.', german: 'Wir haben genug Geld für die Reise.' },
      { italian: 'Avete già un piano per domani?', german: 'Habt ihr schon einen Plan für morgen?' },
      { italian: 'Hanno una casa in campagna.', german: 'Sie haben ein Haus auf dem Land.' },
      { italian: 'Non ho alcuna fretta oggi.', german: 'Ich habe heute keine Eile.' },
      { italian: 'Hai davvero bisogno di questo?', german: 'Brauchst du das wirklich?' },
      { italian: 'Ha un problema con la connessione.', german: 'Er/Sie hat ein Problem mit der Verbindung.' },
      { italian: 'Abbiamo molte cose da fare.', german: 'Wir haben viel zu erledigen.' },
      { italian: 'Ho avuto fame tutto il giorno.', german: 'Ich hatte den ganzen Tag Hunger.' },
      { italian: 'Hai avuto tempo ieri?', german: 'Hattest du gestern Zeit?' },
      { italian: 'Ha avuto sete dopo la corsa.', german: 'Er/Sie hatte nach dem Lauf Durst.' },
      { italian: 'Abbiamo avuto una giornata lunga.', german: 'Wir hatten einen langen Tag.' },
      { italian: 'Avete avuto problemi?', german: 'Hattet ihr Probleme?' },
      { italian: 'Hanno avuto fortuna.', german: 'Sie hatten Glück.' },
      { italian: 'Non ho avuto contanti.', german: 'Ich hatte kein Bargeld.' },
      { italian: 'Hai avuto la mia email?', german: 'Hast du meine E-Mail bekommen?' },
      { italian: 'Ha avuto un\'idea interessante.', german: 'Er/Sie hatte eine interessante Idee.' },
      { italian: 'Abbiamo avuto poco tempo.', german: 'Wir hatten wenig Zeit.' },
      { italian: 'Ho avuto bisogno di aiuto con il progetto.', german: 'Ich brauchte Hilfe beim Projekt.' },
      { italian: 'Hai avuto modo di parlarne?', german: 'Hattest du Gelegenheit, darüber zu sprechen?' },
      { italian: 'Ha avuto spesso mal di testa quest\'inverno.', german: 'Er/Sie hatte diesen Winter oft Kopfschmerzen.' },
      { italian: 'Abbiamo avuto abbastanza soldi per tutto.', german: 'Wir hatten genug Geld für alles.' },
      { italian: 'Avete avuto già un piano o no?', german: 'Hattet ihr schon einen Plan oder nicht?' },
      { italian: 'Hanno avuto una bella esperienza in Italia.', german: 'Sie hatten eine schöne Erfahrung in Italien.' },
      { italian: 'Non ho avuto alcuna fretta ieri.', german: 'Ich hatte gestern keine Eile.' },
      { italian: 'Hai avuto davvero bisogno di questo?', german: 'Hast du das wirklich gebraucht?' },
      { italian: 'Ha avuto un problema tecnico durante la call.', german: 'Er/Sie hatte während des Calls ein technisches Problem.' },
      { italian: 'Abbiamo avuto molte cose da fare.', german: 'Wir hatten viel zu erledigen.' }
    ]
  },

  FARE: {
    name: 'FARE (machen)',
    sentences: [
      { italian: 'Faccio colazione.', german: 'Ich frühstücke.' },
      { italian: 'Fai una pausa adesso?', german: 'Machst du jetzt eine Pause?' },
      { italian: 'Fa caldo oggi.', german: 'Es ist heute heiß.' },
      { italian: 'Facciamo la spesa stasera.', german: 'Wir gehen heute Abend einkaufen.' },
      { italian: 'Fate sport il martedì?', german: 'Macht ihr dienstags Sport?' },
      { italian: 'Fanno molte foto in vacanza.', german: 'Sie machen im Urlaub viele Fotos.' },
      { italian: 'Faccio una torta.', german: 'Ich backe einen Kuchen.' },
      { italian: 'Fai attenzione, per favore.', german: 'Pass bitte auf.' },
      { italian: 'Fa freddo qui dentro?', german: 'Ist es hier drinnen kalt?' },
      { italian: 'Facciamo una passeggiata.', german: 'Wir machen einen Spaziergang.' },
      { italian: 'Faccio spesso una telefonata dopo pranzo.', german: 'Ich telefoniere oft nach dem Mittagessen.' },
      { italian: 'Fai i compiti con tua figlia?', german: 'Machst du die Hausaufgaben mit deiner Tochter?' },
      { italian: 'Fa sempre tardi con le consegne.', german: 'Er/Sie ist mit den Lieferungen immer spät dran.' },
      { italian: 'Facciamo attenzione ai dettagli del contratto.', german: 'Wir achten auf die Details des Vertrags.' },
      { italian: 'Fate ancora quel corso online?', german: 'Macht ihr diesen Online-Kurs noch?' },
      { italian: 'Fanno spesso una pausa lunga.', german: 'Sie machen oft eine lange Pause.' },
      { italian: 'Non faccio rumore quando lavori.', german: 'Ich mache keinen Lärm, wenn du arbeitest.' },
      { italian: 'Fai come preferisci, va bene?', german: 'Mach, wie du magst, okay?' },
      { italian: 'Fa una torta per il compleanno di Luca.', german: 'Er/Sie backt einen Kuchen für Lucas Geburtstag.' },
      { italian: 'Facciamo jogging quando non piove.', german: 'Wir joggen, wenn es nicht regnet.' },
      { italian: 'Ho fatto colazione presto.', german: 'Ich habe früh gefrühstückt.' },
      { italian: 'Hai fatto una pausa?', german: 'Hast du eine Pause gemacht?' },
      { italian: 'Ha fatto caldo tutto il giorno.', german: 'Es war den ganzen Tag heiß.' },
      { italian: 'Abbiamo fatto la spesa ieri.', german: 'Wir haben gestern eingekauft.' },
      { italian: 'Avete fatto sport ieri sera?', german: 'Habt ihr gestern Abend Sport gemacht?' },
      { italian: 'Hanno fatto tante foto.', german: 'Sie haben viele Fotos gemacht.' },
      { italian: 'Ho fatto una torta al cioccolato.', german: 'Ich habe einen Schokokuchen gebacken.' },
      { italian: 'Hai fatto attenzione?', german: 'Hast du aufgepasst?' },
      { italian: 'Ha fatto freddo in montagna.', german: 'Es war kalt in den Bergen.' },
      { italian: 'Abbiamo fatto una passeggiata lunga.', german: 'Wir sind einen langen Spaziergang gegangen.' },
      { italian: 'Ho fatto una telefonata importante.', german: 'Ich habe ein wichtiges Telefonat geführt.' },
      { italian: 'Hai fatto i compiti con tua figlia ieri?', german: 'Hast du gestern die Hausaufgaben mit deiner Tochter gemacht?' },
      { italian: 'Ha fatto tardi con le consegne di nuovo.', german: 'Er/Sie ist mit den Lieferungen wieder spät dran gewesen.' },
      { italian: 'Abbiamo fatto attenzione e non abbiamo sbagliato.', german: 'Wir haben aufgepasst und keinen Fehler gemacht.' },
      { italian: 'Avete fatto ancora quel corso online?', german: 'Habt ihr diesen Online-Kurs noch gemacht?' },
      { italian: 'Hanno fatto una pausa più lunga del solito.', german: 'Sie haben eine längere Pause als üblich gemacht.' },
      { italian: 'Non ho fatto rumore mentre lavoravi.', german: 'Ich habe keinen Lärm gemacht, während du gearbeitet hast.' },
      { italian: 'Hai fatto come preferivi, vero?', german: 'Du hast es so gemacht, wie du wolltest, oder?' },
      { italian: 'Ha fatto una torta per il compleanno di Luca.', german: 'Er/Sie hat einen Kuchen für Lucas Geburtstag gebacken.' },
      { italian: 'Abbiamo fatto jogging nonostante la pioggia.', german: 'Wir sind joggen gegangen, trotz des Regens.' }
    ]
  },

  DIRE: {
    name: 'DIRE (sagen)',
    sentences: [
      { italian: 'Dico la verità.', german: 'Ich sage die Wahrheit.' },
      { italian: 'Dici sempre grazie?', german: 'Sagst du immer Danke?' },
      { italian: 'Dice che arriva alle otto.', german: 'Er/Sie sagt, dass er/sie um acht kommt.' },
      { italian: 'Diciamo buongiorno ai vicini.', german: 'Wir sagen den Nachbarn guten Morgen.' },
      { italian: 'Dite spesso la stessa cosa?', german: 'Sagt ihr oft dasselbe?' },
      { italian: 'Dicono che piove.', german: 'Sie sagen, dass es regnet.' },
      { italian: 'Non dico nulla.', german: 'Ich sage nichts.' },
      { italian: 'Dici che è una buona idea?', german: 'Sagst du, dass es eine gute Idee ist?' },
      { italian: 'Dice sempre la verità.', german: 'Er/Sie sagt immer die Wahrheit.' },
      { italian: 'Diciamo quello che pensiamo.', german: 'Wir sagen, was wir denken.' },
      { italian: 'Dico spesso che il tempo vola.', german: 'Ich sage oft, dass die Zeit fliegt.' },
      { italian: 'Dici a Marco di chiamarmi più tardi?', german: 'Sagst du Marco, er soll mich später anrufen?' },
      { italian: 'Dice ai colleghi di arrivare puntuali.', german: 'Er/Sie sagt den Kollegen, sie sollen pünktlich kommen.' },
      { italian: 'Diciamo chiaramente qual è il problema.', german: 'Wir sagen klar, was das Problem ist.' },
      { italian: 'Dite la vostra opinione senza paura?', german: 'Sagt ihr eure Meinung ohne Angst?' },
      { italian: 'Dicono che la riunione è spostata.', german: 'Sie sagen, dass die Besprechung verschoben ist.' },
      { italian: 'Non dico nulla se non serve.', german: 'Ich sage nichts, wenn es nicht nötig ist.' },
      { italian: 'Dici davvero quello che pensi?', german: 'Sagst du wirklich, was du denkst?' },
      { italian: 'Dice di non avere tempo oggi.', german: 'Er/Sie sagt, dass er/sie heute keine Zeit hat.' },
      { italian: 'Diciamo ai clienti come funziona.', german: 'Wir sagen den Kunden, wie es funktioniert.' },
      { italian: 'Ho detto la verità.', german: 'Ich habe die Wahrheit gesagt.' },
      { italian: 'Hai detto grazie?', german: 'Hast du Danke gesagt?' },
      { italian: 'Ha detto che è arrivato tardi.', german: 'Er/Sie hat gesagt, dass er/sie spät gekommen ist.' },
      { italian: 'Abbiamo detto buongiorno a tutti.', german: 'Wir haben allen guten Morgen gesagt.' },
      { italian: 'Avete detto la stessa cosa?', german: 'Habt ihr dasselbe gesagt?' },
      { italian: 'Hanno detto che pioveva.', german: 'Sie haben gesagt, dass es regnete.' },
      { italian: 'Non ho detto nulla.', german: 'Ich habe nichts gesagt.' },
      { italian: 'Hai detto che era una buona idea?', german: 'Hast du gesagt, dass es eine gute Idee war?' },
      { italian: 'Ha detto sempre la verità.', german: 'Er/Sie hat immer die Wahrheit gesagt.' },
      { italian: 'Abbiamo detto quello che pensavamo.', german: 'Wir haben gesagt, was wir dachten.' },
      { italian: 'Ho detto spesso che era difficile.', german: 'Ich habe oft gesagt, dass es schwierig war.' },
      { italian: 'Hai detto a Marco di richiamarmi?', german: 'Hast du Marco gesagt, er soll mich zurückrufen?' },
      { italian: 'Ha detto ai colleghi di essere puntuali.', german: 'Er/Sie hat den Kollegen gesagt, sie sollen pünktlich sein.' },
      { italian: 'Abbiamo detto chiaramente qual era il problema.', german: 'Wir haben klar gesagt, was das Problem war.' },
      { italian: 'Avete detto la vostra opinione senza paura?', german: 'Habt ihr eure Meinung ohne Angst gesagt?' },
      { italian: 'Hanno detto che la riunione era spostata.', german: 'Sie haben gesagt, dass die Besprechung verschoben war.' },
      { italian: 'Non ho detto nulla perché non serviva.', german: 'Ich habe nichts gesagt, weil es nicht nötig war.' },
      { italian: 'Hai davvero detto quello che pensavi?', german: 'Hast du wirklich gesagt, was du gedacht hast?' },
      { italian: 'Ha detto di non avere tempo ieri.', german: 'Er/Sie hat gesagt, dass er/sie gestern keine Zeit hatte.' },
      { italian: 'Abbiamo detto ai clienti come funzionava.', german: 'Wir haben den Kunden gesagt, wie es funktionierte.' }
    ]
  },

  ANDARE: {
    name: 'ANDARE (gehen)',
    sentences: [
      { italian: 'Vado a casa.', german: 'Ich gehe/fahre nach Hause.' },
      { italian: 'Vai al lavoro in bici?', german: 'Fährst du mit dem Fahrrad zur Arbeit?' },
      { italian: 'Va a scuola ogni giorno.', german: 'Er/Sie geht jeden Tag zur Schule.' },
      { italian: 'Andiamo dal medico oggi.', german: 'Wir gehen heute zum Arzt.' },
      { italian: 'Andate spesso al supermercato?', german: 'Geht ihr oft zum Supermarkt?' },
      { italian: 'Vanno in centro il sabato.', german: 'Sie gehen samstags in die Innenstadt.' },
      { italian: 'Vado a letto presto.', german: 'Ich gehe früh ins Bett.' },
      { italian: 'Vai anche tu?', german: 'Gehst du auch?' },
      { italian: 'Va tutto bene?', german: 'Ist alles in Ordnung?' },
      { italian: 'Andiamo avanti.', german: 'Wir machen weiter.' },
      { italian: 'Vado spesso in palestra dopo il lavoro.', german: 'Ich gehe nach der Arbeit oft ins Fitnessstudio.' },
      { italian: 'Vai a trovare i nonni domani?', german: 'Besuchst du morgen die Großeltern?' },
      { italian: 'Va in centro quando ha tempo.', german: 'Er/Sie geht in die Innenstadt, wenn er/sie Zeit hat.' },
      { italian: 'Andiamo al mare se fa caldo.', german: 'Wir fahren ans Meer, wenn es heiß ist.' },
      { italian: 'Andate a piedi o in bus?', german: 'Geht ihr zu Fuß oder mit dem Bus?' },
      { italian: 'Vanno a cena fuori quando possono.', german: 'Sie gehen essen, wenn sie können.' },
      { italian: 'Non vado se piove troppo.', german: 'Ich gehe nicht, wenn es zu sehr regnet.' },
      { italian: 'Vai pure avanti, ti raggiungo dopo.', german: 'Mach ruhig weiter, ich komme nach.' },
      { italian: 'Va spesso dai clienti fuori città.', german: 'Er/Sie fährt oft zu Kunden außerhalb der Stadt.' },
      { italian: 'Andiamo a vedere la partita stasera?', german: 'Gehen wir heute Abend das Spiel schauen?' },
      { italian: 'Sono andato a casa tardi.', german: 'Ich bin spät nach Hause gegangen/gefahren.' },
      { italian: 'Sei andato al lavoro in bici?', german: 'Bist du mit dem Fahrrad zur Arbeit gefahren?' },
      { italian: 'È andata a scuola ieri.', german: 'Sie ist gestern zur Schule gegangen.' },
      { italian: 'Siamo andati dal medico stamattina.', german: 'Wir sind heute Morgen zum Arzt gegangen.' },
      { italian: 'Siete andati al supermercato?', german: 'Seid ihr zum Supermarkt gegangen?' },
      { italian: 'Sono andati in centro sabato.', german: 'Sie sind am Samstag in die Innenstadt gegangen.' },
      { italian: 'Non sono andato a letto presto.', german: 'Ich bin nicht früh ins Bett gegangen.' },
      { italian: 'Sei andato anche tu?', german: 'Bist du auch gegangen?' },
      { italian: 'È andato tutto bene?', german: 'Ist alles gut gegangen?' },
      { italian: 'Siamo andati avanti con il progetto.', german: 'Wir sind mit dem Projekt vorangekommen.' },
      { italian: 'Sono andato spesso in palestra questa settimana.', german: 'Ich bin diese Woche oft ins Fitnessstudio gegangen.' },
      { italian: 'Sei andato a trovare i nonni domenica?', german: 'Hast du am Sonntag die Großeltern besucht?' },
      { italian: 'È andato in centro perché doveva comprare un regalo.', german: 'Er ist in die Innenstadt gegangen, weil er ein Geschenk kaufen musste.' },
      { italian: 'Siamo andati al mare perché faceva caldo.', german: 'Wir sind ans Meer gefahren, weil es heiß war.' },
      { italian: 'Siete andati a piedi o in bus ieri?', german: 'Seid ihr gestern zu Fuß oder mit dem Bus gegangen?' },
      { italian: 'Sono andati a cena fuori quando hanno potuto.', german: 'Sie sind essen gegangen, wenn sie konnten.' },
      { italian: 'Non sono andato perché pioveva troppo.', german: 'Ich bin nicht gegangen, weil es zu sehr regnete.' },
      { italian: 'Sei andato avanti e ti ho raggiunto dopo?', german: 'Bist du vorausgegangen und ich habe dich später eingeholt?' },
      { italian: 'È andato spesso dai clienti fuori città.', german: 'Er ist oft zu Kunden außerhalb der Stadt gefahren.' },
      { italian: 'Siamo andati a vedere la partita ieri sera.', german: 'Wir sind gestern Abend das Spiel schauen gegangen.' }
    ]
  },

  POTERE: {
    name: 'POTERE (können)',
    sentences: [
      { italian: 'Posso entrare?', german: 'Kann ich reinkommen?' },
      { italian: 'Puoi aiutarmi?', german: 'Kannst du mir helfen?' },
      { italian: 'Può aspettare un attimo.', german: 'Er/Sie kann einen Moment warten.' },
      { italian: 'Possiamo pagare con carta.', german: 'Wir können mit Karte bezahlen.' },
      { italian: 'Potete venire stasera?', german: 'Könnt ihr heute Abend kommen?' },
      { italian: 'Possono uscire dopo cena.', german: 'Sie können nach dem Abendessen ausgehen.' },
      { italian: 'Non posso guidare.', german: 'Ich kann nicht fahren.' },
      { italian: 'Puoi parlare più lentamente?', german: 'Kannst du langsamer sprechen?' },
      { italian: 'Può aprire la finestra?', german: 'Können Sie das Fenster öffnen?' },
      { italian: 'Possiamo vedere più tardi.', german: 'Wir können später sehen/anschauen.' },
      { italian: 'Posso finire il lavoro domattina.', german: 'Ich kann die Arbeit morgen früh fertig machen.' },
      { italian: 'Puoi passare da me dopo il lavoro?', german: 'Kannst du nach der Arbeit bei mir vorbeikommen?' },
      { italian: 'Può spiegare come funziona?', german: 'Kann er/sie erklären, wie es funktioniert?' },
      { italian: 'Possiamo andare via prima, se serve?', german: 'Können wir früher gehen, wenn nötig?' },
      { italian: 'Potete inviarmi il file entro oggi?', german: 'Könnt ihr mir die Datei bis heute schicken?' },
      { italian: 'Possono aspettare finché arrivo.', german: 'Sie können warten, bis ich ankomme.' },
      { italian: 'Non posso promettere nulla adesso.', german: 'Ich kann jetzt nichts versprechen.' },
      { italian: 'Puoi dirmi dove sei?', german: 'Kannst du mir sagen, wo du bist?' },
      { italian: 'Può essere che ci sia un errore?', german: 'Kann es sein, dass es einen Fehler gibt?' },
      { italian: 'Possiamo organizzare una call domani.', german: 'Wir können morgen einen Call organisieren.' },
      { italian: 'Ho potuto entrare.', german: 'Ich konnte reinkommen.' },
      { italian: 'Hai potuto aiutarmi?', german: 'Konntest du mir helfen?' },
      { italian: 'Ha potuto aspettare.', german: 'Er/Sie konnte warten.' },
      { italian: 'Abbiamo potuto pagare con la carta.', german: 'Wir konnten mit Karte bezahlen.' },
      { italian: 'Avete potuto venire?', german: 'Konntet ihr kommen?' },
      { italian: 'Hanno potuto uscire dopo cena.', german: 'Sie konnten nach dem Abendessen ausgehen.' },
      { italian: 'Non ho potuto guidare.', german: 'Ich konnte nicht fahren.' },
      { italian: 'Hai potuto parlare più lentamente?', german: 'Konntest du langsamer sprechen?' },
      { italian: 'Ha potuto aprire la finestra.', german: 'Er/Sie konnte das Fenster öffnen.' },
      { italian: 'Abbiamo potuto vedere più tardi.', german: 'Wir konnten es später ansehen.' },
      { italian: 'Ho potuto finire il lavoro in tempo.', german: 'Ich konnte die Arbeit rechtzeitig beenden.' },
      { italian: 'Hai potuto passare da me dopo il lavoro?', german: 'Konntest du nach der Arbeit bei mir vorbeikommen?' },
      { italian: 'Ha potuto spiegare come funzionava.', german: 'Er/Sie konnte erklären, wie es funktionierte.' },
      { italian: 'Abbiamo potuto andare via prima perché serviva.', german: 'Wir konnten früher gehen, weil es nötig war.' },
      { italian: 'Avete potuto inviarmi il file ieri?', german: 'Konntet ihr mir gestern die Datei schicken?' },
      { italian: 'Hanno potuto aspettare finché sono arrivato.', german: 'Sie konnten warten, bis ich angekommen bin.' },
      { italian: 'Non ho potuto promettere nulla.', german: 'Ich konnte nichts versprechen.' },
      { italian: 'Hai potuto dirmi dove eri?', german: 'Konntest du mir sagen, wo du warst?' },
      { italian: 'È potuto essere un errore di sistema?', german: 'Konnte es ein Systemfehler sein?' },
      { italian: 'Abbiamo potuto organizzare una call domani?', german: 'Konnten wir einen Call für morgen organisieren?' }
    ]
  },

  VOLERE: {
    name: 'VOLERE (wollen)',
    sentences: [
      { italian: 'Voglio un caffè.', german: 'Ich möchte einen Kaffee.' },
      { italian: 'Vuoi uscire stasera?', german: 'Willst du heute Abend ausgehen?' },
      { italian: 'Vuole dormire un po\'.', german: 'Er/Sie will ein wenig schlafen.' },
      { italian: 'Vogliamo imparare l\'italiano.', german: 'Wir möchten Italienisch lernen.' },
      { italian: 'Volete un bicchiere d\'acqua?', german: 'Wollt ihr ein Glas Wasser?' },
      { italian: 'Vogliono parlare con te.', german: 'Sie möchten mit dir sprechen.' },
      { italian: 'Non voglio arrivare tardi.', german: 'Ich will nicht zu spät kommen.' },
      { italian: 'Vuoi davvero quello?', german: 'Willst du das wirklich?' },
      { italian: 'Vuole vedere quel film?', german: 'Will er/sie diesen Film sehen?' },
      { italian: 'Vogliamo andare al parco.', german: 'Wir wollen in den Park gehen.' },
      { italian: 'Voglio comprare un biglietto per domani.', german: 'Ich möchte ein Ticket für morgen kaufen.' },
      { italian: 'Vuoi cenare fuori o a casa?', german: 'Möchtest du auswärts o. zu Hause zu Abend essen?' },
      { italian: 'Vuole provare un ristorante nuovo.', german: 'Er/Sie möchte ein neues Restaurant ausprobieren.' },
      { italian: 'Vogliamo aiutare i nostri amici con il trasloco.', german: 'Wir möchten unseren Freunden beim Umzug helfen.' },
      { italian: 'Volete davvero cambiare piano adesso?', german: 'Wollt ihr den Plan wirklich jetzt ändern?' },
      { italian: 'Vogliono passare il weekend in montagna.', german: 'Sie möchten das Wochenende i.d. Bergen verbringen.' },
      { italian: 'Non voglio spendere troppo per questo.', german: 'Ich möchte dafür nicht zu viel ausgeben.' },
      { italian: 'Vuoi che prenoti il tavolo?', german: 'Willst du, dass ich den Tisch reserviere?' },
      { italian: 'Vuole che arrivi prima delle otto.', german: 'Er/Sie möchte, dass ich vor acht ankomme.' },
      { italian: 'Vogliamo che tutto sia chiaro.', german: 'Wir wollen, dass alles klar ist.' },
      { italian: 'Ho voluto un caffè ma non c\'era.', german: 'Ich wollte einen Kaffee, aber es gab keinen.' },
      { italian: 'Hai voluto uscire ieri?', german: 'Wolltest du gestern ausgehen?' },
      { italian: 'Ha voluto dormire di più.', german: 'Er/Sie wollte mehr schlafen.' },
      { italian: 'Abbiamo voluto imparare l\'italiano da tempo.', german: 'Wir wollten schon lange Italienisch lernen.' },
      { italian: 'Avete voluto un bicchiere d\'acqua?', german: 'Wolltet ihr ein Glas Wasser?' },
      { italian: 'Hanno voluto parlare con te.', german: 'Sie wollten mit dir sprechen.' },
      { italian: 'Non ho voluto arrivare tardi.', german: 'Ich wollte nicht zu spät kommen.' },
      { italian: 'Hai voluto davvero quello?', german: 'Wolltest du das wirklich?' },
      { italian: 'Ha voluto vedere quel film.', german: 'Er/Sie wollte diesen Film sehen.' },
      { italian: 'Abbiamo voluto andare al parco.', german: 'Wir wollten in den Park gehen.' },
      { italian: 'Ho voluto comprare un biglietto, ma era esaurito.', german: 'Ich wollte ein Ticket kaufen, aber es war ausverkauft.' },
      { italian: 'Hai voluto cenare fuori o a casa?', german: 'Wolltest du auswärts oder zu Hause zu Abend essen?' },
      { italian: 'Ha voluto provare un ristorante nuovo ieri.', german: 'Er/Sie wollte gestern ein neues Restaurant ausprobieren.' },
      { italian: 'Abbiamo voluto aiutare gli amici con il trasloco.', german: 'Wir wollten den Freunden beim Umzug helfen.' },
      { italian: 'Avete voluto davvero cambiare piano?', german: 'Wolltet ihr wirklich den Plan ändern?' },
      { italian: 'Hanno voluto passare il weekend in montagna.', german: 'Sie wollten das Wochenende in den Bergen verbringen.' },
      { italian: 'Non ho voluto spendere troppo.', german: 'Ich wollte nicht zu viel ausgeben.' },
      { italian: 'Hai voluto che prenotassi il tavolo?', german: 'Wolltest du, dass ich den Tisch reserviere?' },
      { italian: 'Ha voluto che arrivassi prima delle otto.', german: 'Er/Sie wollte, dass ich vor acht ankam.' },
      { italian: 'Abbiamo voluto che tutto fosse chiaro.', german: 'Wir wollten, dass alles klar war.' }
    ]
  },

  DOVERE: {
    name: 'DOVERE (müssen)',
    sentences: [
      { italian: 'Devo lavorare.', german: 'Ich muss arbeiten.' },
      { italian: 'Devi studiare oggi?', german: 'Musst du heute lernen?' },
      { italian: 'Deve andare ora.', german: 'Er/Sie muss jetzt gehen.' },
      { italian: 'Dobbiamo pagare l\'affitto.', german: 'Wir müssen die Miete zahlen.' },
      { italian: 'Dovete chiamare tua madre?', german: 'Müsst ihr deine Mutter anrufen?' },
      { italian: 'Devono partire domani.', german: 'Sie müssen morgen abreisen.' },
      { italian: 'Non devo dimenticare le chiavi.', german: 'Ich darf die Schlüssel nicht vergessen.' },
      { italian: 'Devi venire con noi?', german: 'Musst du mit uns kommen?' },
      { italian: 'Deve finire prima delle sei.', german: 'Er/Sie muss vor sechs fertig werden.' },
      { italian: 'Dobbiamo studiare di più.', german: 'Wir müssen mehr lernen.' },
      { italian: 'Devo consegnare il progetto entro domani.', german: 'Ich muss das Projekt bis morgen abgeben.' },
      { italian: 'Devi davvero partire così presto?', german: 'Musst du wirklich so früh los?' },
      { italian: 'Deve prendere l\'autobus delle otto.', german: 'Er/Sie muss den Acht-Uhr-Bus nehmen.' },
      { italian: 'Dobbiamo rispettare le scadenze.', german: 'Wir müssen die Fristen einhalten.' },
      { italian: 'Dovete portare i documenti alla riunione?', german: 'Müsst ihr die Unterlagen zum Meeting mitbringen?' },
      { italian: 'Devono cambiare piano se piove.', german: 'Sie müssen den Plan ändern, wenn es regnet.' },
      { italian: 'Non devo mangiare troppo zucchero.', german: 'Ich darf nicht zu viel Zucker essen.' },
      { italian: 'Devi ricordarti di scrivere a Luca.', german: 'Du musst daran denken, Luca zu schreiben.' },
      { italian: 'Deve essere difficile per te?', german: 'Muss es für dich schwierig sein?' },
      { italian: 'Dobbiamo parlare con il cliente oggi pomeriggio.', german: 'Wir müssen heute Nachmittag mit dem Kunden sprechen.' },
      { italian: 'Ho dovuto lavorare fino a tardi.', german: 'Ich musste bis spät arbeiten.' },
      { italian: 'Hai dovuto studiare ieri?', german: 'Musstest du gestern lernen?' },
      { italian: 'Ha dovuto andare subito.', german: 'Er/Sie musste sofort gehen.' },
      { italian: 'Abbiamo dovuto pagare l\'affitto ieri.', german: 'Wir mussten gestern die Miete zahlen.' },
      { italian: 'Avete dovuto chiamare vostra madre?', german: 'Musstet ihr eure Mutter anrufen?' },
      { italian: 'Hanno dovuto partire stamattina.', german: 'Sie mussten heute Morgen abreisen.' },
      { italian: 'Non ho dovuto aspettare molto.', german: 'Ich musste nicht lange warten.' },
      { italian: 'Hai dovuto venire con noi?', german: 'Musstest du mit uns kommen?' },
      { italian: 'Ha dovuto finire prima delle sei.', german: 'Er/Sie musste vor sechs fertig werden.' },
      { italian: 'Abbiamo dovuto studiare di più.', german: 'Wir mussten mehr lernen.' },
      { italian: 'Ho dovuto consegnare il progetto entro ieri.', german: 'Ich musste das Projekt bis gestern abgeben.' },
      { italian: 'Hai dovuto davvero partire così presto?', german: 'Musstest du wirklich so früh los?' },
      { italian: 'Ha dovuto prendere l\'autobus delle otto.', german: 'Er/Sie musste den Acht-Uhr-Bus nehmen.' },
      { italian: 'Abbiamo dovuto rispettare tutte le scadenze.', german: 'Wir mussten alle Fristen einhalten.' },
      { italian: 'Avete dovuto portare i documenti alla riunione?', german: 'Musstet ihr die Unterlagen zum Meeting mitbringen?' },
      { italian: 'Hanno dovuto cambiare piano per la pioggia.', german: 'Sie mussten wegen des Regens den Plan ändern.' },
      { italian: 'Non ho dovuto mangiare zucchero per una settimana.', german: 'Ich durfte eine Woche lang keinen Zucker essen.' },
      { italian: 'Hai dovuto ricordarti di scrivere a Luca?', german: 'Musstest du daran denken, Luca zu schreiben?' },
      { italian: 'È dovuto essere complicato per te?', german: 'Musste es kompliziert für dich gewesen sein?' },
      { italian: 'Abbiamo dovuto parlare con il cliente per ore.', german: 'Wir mussten stundenlang mit dem Kunden sprechen.' }
    ]
  },

  STARE: {
    name: 'STARE (bleiben)',
    sentences: [
      { italian: 'Sto bene.', german: 'Mir geht es gut.' },
      { italian: 'Stai a casa oggi?', german: 'Bleibst du heute zu Hause?' },
      { italian: 'Sta male.', german: 'Ihm/Ihr geht es schlecht.' },
      { italian: 'Stiamo in ufficio.', german: 'Wir sind/bleiben im Büro.' },
      { italian: 'State attenti, per favore.', german: 'Passt bitte auf.' },
      { italian: 'Stanno zitti.', german: 'Sie sind still.' },
      { italian: 'Non sto scherzando.', german: 'Ich mache keinen Spaß.' },
      { italian: 'Stai aspettando l\'autobus?', german: 'Wartest du auf den Bus?' },
      { italian: 'Sta con noi stasera.', german: 'Er/Sie ist heute Abend bei uns.' },
      { italian: 'Stiamo bene, grazie.', german: 'Uns geht es gut, danke.' },
      { italian: 'Sto imparando l\'italiano da qualche mese.', german: 'Ich lerne seit einigen Monaten Italienisch.' },
      { italian: 'Stai ancora cercando lavoro?', german: 'Suchst du immer noch Arbeit?' },
      { italian: 'Sta lavorando da remoto oggi.', german: 'Er/Sie arbeitet heute remote.' },
      { italian: 'Stiamo organizzando una cena per sabato.', german: 'Wir organisieren ein Abendessen für Samstag.' },
      { italian: 'State davvero bene con quel colore?', german: 'Steht euch diese Farbe wirklich gut?' },
      { italian: 'Stanno facendo una pausa lunga.', german: 'Sie machen eine lange Pause.' },
      { italian: 'Non sto molto bene stamattina.', german: 'Mir geht es heute Morgen nicht so gut.' },
      { italian: 'Stai dicendo la verità?', german: 'Sagst du die Wahrheit?' },
      { italian: 'Sta per piovere tra poco.', german: 'Es wird gleich regnen.' },
      { italian: 'Stiamo per uscire, vieni?', german: 'Wir gehen gleich los, kommst du?' },
      { italian: 'Sono stato bene ieri.', german: 'Mir ging es gestern gut.' },
      { italian: 'Sei stato a casa oggi?', german: 'Warst du heute zu Hause?' },
      { italian: 'È stata male la settimana scorsa.', german: 'Ihr ging es letzte Woche schlecht.' },
      { italian: 'Siamo stati in ufficio fino alle sei.', german: 'Wir waren bis sechs im Büro.' },
      { italian: 'Siete stati attenti durante la lezione?', german: 'Wart ihr während des Unterrichts aufmerksam?' },
      { italian: 'Sono stati zitti in riunione.', german: 'Sie waren in der Besprechung still.' },
      { italian: 'Non sono stato a scherzare.', german: 'Ich habe keinen Spaß gemacht / Es war mein Ernst.' },
      { italian: 'Sei stato ad aspettare molto?', german: 'Hast du lange gewartet?' },
      { italian: 'È stato con noi tutta la sera.', german: 'Er war den ganzen Abend bei uns.' },
      { italian: 'Siamo stati bene, grazie.', german: 'Uns ging es gut, danke.' },
      { italian: 'Sono stato a imparare l\'italiano con un corso intensivo.', german: 'Ich habe Italienisch mit einem Intensivkurs gelernt.' },
      { italian: 'Sei stato ancora a cercare lavoro la scorsa estate?', german: 'Hast du letzten Sommer weiter nach Arbeit gesucht?' },
      { italian: 'È stato a lavorare da remoto per due settimane.', german: 'Er hat zwei Wochen remote gearbeitet.' },
      { italian: 'Siamo stati a organizzare una cena per sabato.', german: 'Wir haben ein Abendessen für Samstag organisiert.' },
      { italian: 'Siete stati davvero bene con quel colore ieri?', german: 'Hat euch diese Farbe gestern wirklich gut gestanden?' },
      { italian: 'Sono stati a fare una pausa lunga dopo pranzo.', german: 'Sie haben nach dem Mittagessen eine lange Pause gemacht.' },
      { italian: 'Non sono stato molto bene stamattina.', german: 'Mir ging es heute Morgen nicht sehr gut.' },
      { italian: 'Sei stato a dire la verità davanti a tutti?', german: 'Hast du vor allen die Wahrheit gesagt?' },
      { italian: 'È stato per piovere e poi ha smesso.', german: 'Es fing an zu regnen und hörte dann auf.' },
      { italian: 'Siamo stati per uscire quando hai chiamato.', german: 'Wir wollten gerade gehen, als du angerufen hast.' }
    ]
  },

  VENIRE: {
    name: 'VENIRE (kommen)',
    sentences: [
      { italian: 'Vengo subito.', german: 'Ich komme sofort.' },
      { italian: 'Vieni anche tu?', german: 'Kommst du auch?' },
      { italian: 'Viene in treno.', german: 'Er/Sie kommt mit dem Zug.' },
      { italian: 'Veniamo a casa tua.', german: 'Wir kommen zu dir nach Hause.' },
      { italian: 'Venite stasera?', german: 'Kommt ihr heute Abend?' },
      { italian: 'Vengono con noi.', german: 'Sie kommen mit uns.' },
      { italian: 'Non vengo domani.', german: 'Ich komme morgen nicht.' },
      { italian: 'Vieni presto, per favore.', german: 'Komm bitte früh.' },
      { italian: 'Viene anche Marco?', german: 'Kommt Marco auch?' },
      { italian: 'Veniamo volentieri.', german: 'Wir kommen gern.' },
      { italian: 'Vengo quando finisco il lavoro.', german: 'Ich komme, wenn ich mit der Arbeit fertig bin.' },
      { italian: 'Vieni se ti fa piacere.', german: 'Komm, wenn es dir recht ist.' },
      { italian: 'Viene a vedere la partita stasera.', german: 'Er/Sie kommt heute Abend, um das Spiel zu sehen.' },
      { italian: 'Veniamo spesso qui il sabato.', german: 'Wir kommen samstags oft hierher.' },
      { italian: 'Venite con la macchina o in treno?', german: 'Kommt ihr mit dem Auto oder mit dem Zug?' },
      { italian: 'Vengono solo se c\'è tempo.', german: 'Sie kommen nur, wenn Zeit ist.' },
      { italian: 'Non vengo se piove troppo.', german: 'Ich komme nicht, wenn es zu sehr regnet.' },
      { italian: 'Vieni pure, ti aspettiamo.', german: 'Komm ruhig, wir warten auf dich.' },
      { italian: 'Viene spesso dai clienti fuori città.', german: 'Er/Sie kommt oft zu Kunden außerhalb der Stadt.' },
      { italian: 'Veniamo a salutarti domani mattina?', german: 'Kommen wir dich morgen früh grüßen?' },
      { italian: 'Sono venuto subito.', german: 'Ich bin sofort gekommen.' },
      { italian: 'Sei venuto anche tu?', german: 'Bist du auch gekommen?' },
      { italian: 'È venuta in treno.', german: 'Sie ist mit dem Zug gekommen.' },
      { italian: 'Siamo venuti a casa tua ieri.', german: 'Wir sind gestern zu dir nach Hause gekommen.' },
      { italian: 'Siete venuti stasera?', german: 'Seid ihr heute Abend gekommen?' },
      { italian: 'Sono venuti con noi.', german: 'Sie sind mit uns gekommen.' },
      { italian: 'Non sono venuto ieri.', german: 'Ich bin gestern nicht gekommen.' },
      { italian: 'Sei venuto presto?', german: 'Bist du früh gekommen?' },
      { italian: 'È venuto anche Marco.', german: 'Auch Marco ist gekommen.' },
      { italian: 'Siamo venuti volentieri.', german: 'Wir sind gern gekommen.' },
      { italian: 'Sono venuto quando ho finito il lavoro.', german: 'Ich bin gekommen, als ich mit der Arbeit fertig war.' },
      { italian: 'Sei venuto se ti faceva piacere?', german: 'Bist du gekommen, wenn es dir recht war?' },
      { italian: 'È venuto a vedere la partita ieri sera.', german: 'Er ist gestern Abend gekommen, um das Spiel zu sehen.' },
      { italian: 'Siamo venuti spesso qui l\'anno scorso.', german: 'Wir sind letztes Jahr oft hierher gekommen.' },
      { italian: 'Siete venuti con la macchina o in treno?', german: 'Seid ihr mit dem Auto oder mit dem Zug gekommen?' },
      { italian: 'Sono venuti solo se c\'era tempo.', german: 'Sie sind nur gekommen, wenn Zeit war.' },
      { italian: 'Non sono venuto perché pioveva troppo.', german: 'Ich bin nicht gekommen, weil es zu sehr regnete.' },
      { italian: 'Sei venuto pure, ti abbiamo aspettato.', german: 'Du bist trotzdem gekommen; wir haben auf dich gewartet.' },
      { italian: 'È venuto spesso dai clienti fuori città.', german: 'Er ist oft zu Kunden außerhalb der Stadt gekommen.' },
      { italian: 'Siamo venuti a salutarti ieri mattina.', german: 'Wir sind gestern früh gekommen, um dich zu grüßen.' }
    ]
  },

  SAPERE: {
    name: 'SAPERE (wissen)',
    sentences: [
      { italian: 'So la risposta.', german: 'Ich weiß die Antwort.' },
      { italian: 'Sai dov\'è la stazione?', german: 'Weißt du, wo der Bahnhof ist?' },
      { italian: 'Sa parlare tedesco.', german: 'Er/Sie kann Deutsch sprechen.' },
      { italian: 'Sappiamo poco di questo.', german: 'Wir wissen wenig darüber.' },
      { italian: 'Sapete che ora è?', german: 'Wisst ihr, wie spät es ist?' },
      { italian: 'Sanno nuotare.', german: 'Sie können schwimmen.' },
      { italian: 'Non so il tuo numero.', german: 'Ich weiß deine Nummer nicht.' },
      { italian: 'Sai come si fa?', german: 'Weißt du, wie man das macht?' },
      { italian: 'Sa chi è?', german: 'Weiß er/sie, wer das ist?' },
      { italian: 'Sappiamo che sei occupato.', german: 'Wir wissen, dass du beschäftigt bist.' },
      { italian: 'So che oggi piove.', german: 'Ich weiß, dass es heute regnet.' },
      { italian: 'Sai se puoi venire domani?', german: 'Weißt du, ob du morgen kommen kannst?' },
      { italian: 'Sa perché sei preoccupato.', german: 'Er/Sie weiß, warum du besorgt bist.' },
      { italian: 'Sappiamo come funziona il sistema.', german: 'Wir wissen, wie das System funktioniert.' },
      { italian: 'Sapete davvero quanto costa?', german: 'Wisst ihr wirklich, wie viel es kostet?' },
      { italian: 'Sanno che non ho tempo adesso.', german: 'Sie wissen, dass ich jetzt keine Zeit habe.' },
      { italian: 'Non so se sia la scelta giusta.', german: 'Ich weiß nicht, ob es die richtige Wahl ist.' },
      { italian: 'Sai perché è importante?', german: 'Weißt du, warum es wichtig ist?' },
      { italian: 'Sa dove dobbiamo andare.', german: 'Er/Sie weiß, wohin wir gehen müssen.' },
      { italian: 'Sappiamo di avere una scadenza domani.', german: 'Wir wissen, dass wir morgen eine Frist haben.' },
      { italian: 'Ho saputo la risposta.', german: 'Ich habe die Antwort erfahren.' },
      { italian: 'Hai saputo dov\'era la stazione?', german: 'Hast du erfahren, wo der Bahnhof war?' },
      { italian: 'Ha saputo la notizia ieri.', german: 'Er/Sie hat die Nachricht gestern erfahren.' },
      { italian: 'Abbiamo saputo poco all\'inizio.', german: 'Wir haben am Anfang wenig erfahren.' },
      { italian: 'Avete saputo che ora era?', german: 'Habt ihr gewusst, wie spät es war?' },
      { italian: 'Hanno saputo nuotare da piccoli.', german: 'Sie konnten als Kinder schwimmen (haben es gelernt).' },
      { italian: 'Non ho saputo il tuo numero.', german: 'Ich habe deine Nummer nicht erfahren.' },
      { italian: 'Hai saputo come si faceva?', german: 'Hast du erfahren, wie man es machte?' },
      { italian: 'Ha saputo chi era.', german: 'Er/Sie hat erfahren, wer es war.' },
      { italian: 'Abbiamo saputo che eri occupato.', german: 'Wir haben erfahren, dass du beschäftigt warst.' },
      { italian: 'Ho saputo che oggi pioveva.', german: 'Ich habe erfahren, dass es heute regnete.' },
      { italian: 'Hai saputo se potevi venire domani?', german: 'Hast du erfahren, ob du morgen kommen konntest?' },
      { italian: 'Ha saputo perché eri preoccupato.', german: 'Er/Sie hat erfahren, warum du besorgt warst.' },
      { italian: 'Abbiamo saputo come funzionava il sistema.', german: 'Wir haben erfahren, wie das System funktionierte.' },
      { italian: 'Avete saputo davvero quanto costava?', german: 'Habt ihr wirklich erfahren, wie viel es kostete?' },
      { italian: 'Hanno saputo che non avevo tempo allora.', german: 'Sie haben erfahren, dass ich damals keine Zeit hatte.' },
      { italian: 'Non ho saputo se fosse la scelta giusta.', german: 'Ich habe nicht erfahren, ob es die richtige Wahl war.' },
      { italian: 'Hai saputo perché era importante?', german: 'Hast du erfahren, warum es wichtig war?' },
      { italian: 'Ha saputo dove dovevamo andare.', german: 'Er/Sie hat erfahren, wohin wir gehen mussten.' },
      { italian: 'Abbiamo saputo della scadenza solo ieri.', german: 'Wir haben erst gestern von der Frist erfahren.' }
    ]
  },

  VEDERE: {
    name: 'VEDERE (sehen)',
    sentences: [
      { italian: 'Vedo la luna.', german: 'Ich sehe den Mond.' },
      { italian: 'Vedi il mio messaggio?', german: 'Siehst du meine Nachricht?' },
      { italian: 'Vede bene senza occhiali.', german: 'Er/Sie sieht ohne Brille gut.' },
      { italian: 'Vediamo un film stasera.', german: 'Wir schauen heute Abend einen Film.' },
      { italian: 'Vedete qualche problema?', german: 'Seht ihr irgendwelche Probleme?' },
      { italian: 'Vedono spesso i nonni.', german: 'Sie sehen oft die Großeltern.' },
      { italian: 'Non vedo nessuno.', german: 'Ich sehe niemanden.' },
      { italian: 'Vedi la differenza?', german: 'Siehst du den Unterschied?' },
      { italian: 'Vede che sei stanco.', german: 'Er/Sie sieht, dass du müde bist.' },
      { italian: 'Vediamo il mare dalla finestra.', german: 'Wir sehen das Meer aus dem Fenster.' },
      { italian: 'Vedo quello che intendi.', german: 'Ich sehe, was du meinst.' },
      { italian: 'Vedi spesso i tuoi amici?', german: 'Siehst du deine Freunde oft?' },
      { italian: 'Vede che non ho tempo.', german: 'Er/Sie sieht, dass ich keine Zeit habe.' },
      { italian: 'Vediamo chiaramente i risultati.', german: 'Wir sehen die Ergebnisse klar.' },
      { italian: 'Vedete davvero un miglioramento?', german: 'Seht ihr wirklich eine Verbesserung?' },
      { italian: 'Vedono il problema ma non la soluzione.', german: 'Sie sehen das Problem, aber nicht die Lösung.' },
      { italian: 'Non vedo perché dovremmo aspettare.', german: 'Ich sehe nicht, warum wir warten sollten.' },
      { italian: 'Vedi dove sto andando?', german: 'Siehst du, wohin ich gehe?' },
      { italian: 'Vede che tutto funziona.', german: 'Er/Sie sieht, dass alles funktioniert.' },
      { italian: 'Vediamo se è possibile farlo oggi.', german: 'Wir schauen, ob es heute möglich ist.' },
      { italian: 'Ho visto la luna ieri.', german: 'Ich habe gestern den Mond gesehen.' },
      { italian: 'Hai visto il mio messaggio?', german: 'Hast du meine Nachricht gesehen?' },
      { italian: 'Ha visto bene il film.', german: 'Er/Sie hat den Film gut gesehen/verstanden.' },
      { italian: 'Abbiamo visto un film ieri sera.', german: 'Wir haben gestern Abend einen Film gesehen.' },
      { italian: 'Avete visto qualche problema?', german: 'Habt ihr irgendwelche Probleme gesehen?' },
      { italian: 'Hanno visto spesso i nonni quest\'estate.', german: 'Sie haben diesen Sommer oft die Großeltern gesehen.' },
      { italian: 'Non ho visto nessuno.', german: 'Ich habe niemanden gesehen.' },
      { italian: 'Hai visto la differenza?', german: 'Hast du den Unterschied gesehen?' },
      { italian: 'Ha visto che eri stanco.', german: 'Er/Sie hat gesehen, dass du müde warst.' },
      { italian: 'Abbiamo visto il mare dalla finestra.', german: 'Wir haben das Meer aus dem Fenster gesehen.' },
      { italian: 'Ho visto quello che intendevi.', german: 'Ich habe gesehen, was du meintest.' },
      { italian: 'Hai visto spesso i tuoi amici ultimamente?', german: 'Hast du in letzter Zeit deine Freunde oft gesehen?' },
      { italian: 'Ha visto che non avevo tempo.', german: 'Er/Sie hat gesehen, dass ich keine Zeit hatte.' },
      { italian: 'Abbiamo visto chiaramente i risultati del test.', german: 'Wir haben die Testergebnisse klar gesehen.' },
      { italian: 'Avete visto davvero un miglioramento?', german: 'Habt ihr wirklich eine Verbesserung gesehen?' },
      { italian: 'Hanno visto il problema ma non la soluzione.', german: 'Sie haben das Problem gesehen, aber nicht die Lösung.' },
      { italian: 'Non ho visto perché dovessimo aspettare.', german: 'Ich habe nicht gesehen, warum wir warten sollten.' },
      { italian: 'Hai visto dove stavo andando?', german: 'Hast du gesehen, wohin ich ging?' },
      { italian: 'Ha visto che tutto funzionava.', german: 'Er/Sie hat gesehen, dass alles funktionierte.' },
      { italian: 'Abbiamo visto che era possibile farlo ieri.', german: 'Wir haben gesehen, dass es gestern möglich war.' }
    ]
  },

  USCIRE: {
    name: 'USCIRE (ausgehen)',
    sentences: [
      { italian: 'Esco ora.', german: 'Ich gehe jetzt raus.' },
      { italian: 'Esci stasera?', german: 'Gehst du heute Abend aus?' },
      { italian: 'Esce con gli amici.', german: 'Er/Sie geht mit Freunden aus.' },
      { italian: 'Usciamo a fare una passeggiata.', german: 'Wir gehen spazieren.' },
      { italian: 'Uscite dopo cena?', german: 'Geht ihr nach dem Abendessen aus?' },
      { italian: 'Escono presto domani.', german: 'Sie gehen morgen früh raus.' },
      { italian: 'Non esco con questo tempo.', german: 'Ich gehe bei diesem Wetter nicht raus.' },
      { italian: 'Esci anche tu con noi?', german: 'Gehst du auch mit uns aus?' },
      { italian: 'Esce adesso o più tardi?', german: 'Geht er/sie jetzt oder später raus?' },
      { italian: 'Usciamo quando finiamo di lavorare.', german: 'Wir gehen raus, wenn wir mit der Arbeit fertig sind.' },
      { italian: 'Esco spesso in bicicletta la domenica.', german: 'Ich fahre sonntags oft mit dem Fahrrad raus.' },
      { italian: 'Esci solo per fare la spesa?', german: 'Gehst du nur zum Einkaufen raus?' },
      { italian: 'Esce anche se piove.', german: 'Er/Sie geht auch raus, wenn es regnet.' },
      { italian: 'Usciamo volentieri nel weekend.', german: 'Wir gehen am Wochenende gern aus.' },
      { italian: 'Uscite a piedi o in macchina?', german: 'Geht ihr zu Fuß oder fahrt ihr mit dem Auto?' },
      { italian: 'Escono quando hanno tempo.', german: 'Sie gehen raus, wenn sie Zeit haben.' },
      { italian: 'Non esco se fa troppo freddo.', german: 'Ich gehe nicht raus, wenn es zu kalt ist.' },
      { italian: 'Esci presto così eviti il traffico?', german: 'Gehst du früh los, um den Verkehr zu vermeiden?' },
      { italian: 'Esce spesso con i colleghi dopo il lavoro.', german: 'Er/Sie geht nach der Arbeit oft mit Kollegen aus.' },
      { italian: 'Usciamo a vedere un film stasera?', german: 'Gehen wir heute Abend einen Film schauen?' },
      { italian: 'Sono uscito presto.', german: 'Ich bin früh rausgegangen.' },
      { italian: 'Sei uscito ieri sera?', german: 'Bist du gestern Abend ausgegangen?' },
      { italian: 'È uscita con gli amici.', german: 'Sie ist mit Freunden ausgegangen.' },
      { italian: 'Siamo usciti a fare una passeggiata.', german: 'Wir sind spazieren gegangen.' },
      { italian: 'Siete usciti dopo cena?', german: 'Seid ihr nach dem Abendessen ausgegangen?' },
      { italian: 'Sono usciti presto stamattina.', german: 'Sie sind heute Morgen früh rausgegangen.' },
      { italian: 'Non sono uscito con quel tempo.', german: 'Ich bin bei dem Wetter nicht rausgegangen.' },
      { italian: 'Sei uscito anche tu con noi?', german: 'Bist du auch mit uns ausgegangen?' },
      { italian: 'È uscito adesso o più tardi?', german: 'Ist er jetzt oder später rausgegangen?' },
      { italian: 'Siamo usciti quando abbiamo finito di lavorare.', german: 'Wir sind rausgegangen, als wir mit der Arbeit fertig waren.' },
      { italian: 'Sono uscito spesso in bicicletta la domenica scorsa.', german: 'Ich bin letzten Sonntag oft mit dem Fahrrad rausgefahren.' },
      { italian: 'Sei uscito solo per fare la spesa?', german: 'Bist du nur zum Einkaufen rausgegangen?' },
      { italian: 'È uscita anche se pioveva.', german: 'Sie ist rausgegangen, obwohl es regnete.' },
      { italian: 'Siamo usciti volentieri nel weekend.', german: 'Wir sind am Wochenende gern ausgegangen.' },
      { italian: 'Siete usciti a piedi o in macchina?', german: 'Seid ihr zu Fuß gegangen oder mit dem Auto gefahren?' },
      { italian: 'Sono usciti quando avevano tempo.', german: 'Sie sind rausgegangen, wenn sie Zeit hatten.' },
      { italian: 'Non sono uscito perché faceva troppo freddo.', german: 'Ich bin nicht rausgegangen, weil es zu kalt war.' },
      { italian: 'Sei uscito presto per evitare il traffico?', german: 'Bist du früh losgegangen, um den Verkehr zu vermeiden?' },
      { italian: 'È uscito spesso con i colleghi dopo il lavoro.', german: 'Er ist nach der Arbeit oft mit Kollegen ausgegangen.' },
      { italian: 'Siamo usciti a vedere un film ieri sera.', german: 'Wir sind gestern Abend einen Film schauen gegangen.' }
    ]
  },

  DARE: {
    name: 'DARE (geben)',
    sentences: [
      { italian: 'Te lo do appena posso.', german: 'Ich gebe es dir, sobald ich kann.' },
      { italian: 'Non te lo posso dare adesso.', german: 'Ich kann es dir jetzt nicht geben.' },
      { italian: 'Me lo dai un attimo?', german: 'Gibst du es mir kurz?' },
      { italian: 'Glielo do io, non ti preoccupare.', german: 'Ich gebe es ihm/ihr, keine Sorge.' },
      { italian: 'Ce lo danno domani.', german: 'Sie geben es uns morgen.' },
      { italian: 'Te ne do uno migliore.', german: 'Ich gebe dir ein besseres.' },
      { italian: 'Me ne dai un altro?', german: 'Gibst du mir noch eins?' },
      { italian: 'Se vuoi, te lo do io.', german: 'Wenn du willst, gebe ich es dir.' },
      { italian: 'Ce lo porta tra un attimo.', german: 'Er/Sie bringt es uns gleich.' },
      { italian: 'Glielo può dare lei?', german: 'Können Sie es ihm/ihr geben?' },
      { italian: 'Me lo dà senza zucchero.', german: 'Geben Sie es mir ohne Zucker.' },
      { italian: 'Ce ne dà due, per favore.', german: 'Geben Sie uns bitte zwei davon.' },
      { italian: 'Glieli do subito.', german: 'Ich gebe sie ihm/ihr sofort.' },
      { italian: 'Me li incarta? Poi glieli do io.', german: 'Packen Sie sie mir ein? Dann gebe ich sie ihm/ihr.' },
      { italian: "Gliel'ho già dato ieri.", german: 'Ich habe es ihm/ihr gestern schon gegeben.' },
      { italian: 'Non gliene darei troppa importanza.', german: 'Ich würde dem nicht zu viel Bedeutung beimessen.' },
      { italian: 'Te ne do uno io, tanto non lo uso.', german: 'Ich gebe dir eins, ich benutze es sowieso nicht.' },
      { italian: 'Se lo vedi, daglielo da parte mia.', german: 'Wenn du ihn/sie siehst, gib es ihm/ihr von mir.' },
      { italian: 'Non glielo dire adesso, poi glielo do io.', german: 'Sag es ihm/ihr jetzt nicht, ich sage es ihm/ihr später.' },
      { italian: 'Te lo do come consiglio.', german: 'Ich gebe dir das als Rat.' },
      { italian: 'Te lo dico sinceramente.', german: 'Ich sage es dir ehrlich.' },
      { italian: 'Non me ne darei la colpa.', german: 'Ich würde mir dafür keine Schuld geben.' },
      { italian: 'Glielo do per certo.', german: 'Ich halte es für sicher.' },
      { italian: 'Te ne do atto.', german: 'Ich erkenne das an.' },
      { italian: 'Non gliene do molta fiducia.', german: 'Ich habe nicht viel Vertrauen darin.' },
      { italian: 'Me lo dai come sicuro?', german: 'Gibst du mir das als sicher an?' },
      { italian: 'Te lo faccio sapere e te lo do per confermato.', german: 'Ich sage dir Bescheid und bestätige es dir.' },
      { italian: 'Appena ce lo danno, ti avviso.', german: 'Sobald sie es uns geben, sage ich dir Bescheid.' },
      { italian: 'Te ne do comunicazione domani.', german: 'Ich informiere dich morgen darüber.' },
      { italian: 'Se ce lo danno in tempo, partiamo.', german: 'Wenn sie es uns rechtzeitig geben, fahren wir los.' },
      { italian: 'Te lo do entro sera.', german: 'Ich gebe es dir bis heute Abend.' },
      { italian: 'Dammelo pure, poi glielo do io.', german: 'Gib es mir ruhig, dann gebe ich es ihm/ihr.' },
      { italian: 'Non te lo sto dando per scontato.', german: 'Ich nehme das dir gegenüber nicht als selbstverständlich an.' },
      { italian: 'Te ne do uno al volo.', german: 'Ich gebe dir schnell eins.' },
      { italian: 'Glielo dai tu o glielo do io?', german: 'Gibst du es ihm/ihr oder soll ich es geben?' },
      { italian: 'Me lo sono fatto dare ieri.', german: 'Ich habe es mir gestern geben lassen.' },
      { italian: 'Te lo do per buono.', german: 'Ich halte es für akzeptabel.' },
      { italian: 'Non gliene do più di tanto.', german: 'Ich messe dem nicht allzu viel Bedeutung bei.' },
      { italian: 'Te lo do come fatto.', german: 'Ich betrachte es als erledigt.' },
      { italian: 'Ce lo siamo già dati.', german: 'Wir haben es uns schon gegeben.' }
    ]
  },

  TROVARE: {
    name: 'TROVARE (finden)',
    sentences: [
      { italian: 'Lo trovo molto interessante.', german: 'Ich finde es sehr interessant.' },
      { italian: 'Non lo trovo giusto.', german: 'Ich finde es nicht richtig.' },
      { italian: 'Me lo trovi strano?', german: 'Findest du es seltsam?' },
      { italian: 'Te lo trovo io subito.', german: 'Ich finde es dir sofort.' },
      { italian: 'Non me lo trovo più.', german: 'Ich finde es nicht mehr.' },
      { italian: 'Ce lo troviamo domani.', german: 'Wir finden es morgen.' },
      { italian: 'Me ne trovi uno migliore?', german: 'Findest du mir ein besseres?' },
      { italian: 'Non lo trovo facile da fare.', german: 'Ich finde es nicht einfach zu machen.' },
      { italian: 'Te lo trovi bene qui?', german: 'Fühlst du dich hier wohl? / Findest du dich hier gut zurecht?' },
      { italian: 'Non glielo trovo necessario.', german: 'Ich halte es ihm/ihr gegenüber nicht für notwendig.' },
      { italian: "Me lo sono trovato davanti all'improvviso.", german: 'Ich habe es plötzlich vor mir gefunden.' },
      { italian: 'Non me ne trovo bene.', german: 'Ich komme damit nicht gut zurecht.' },
      { italian: 'Te lo trovo un po\' caro.', german: 'Ich finde es dir etwas teuer.' },
      { italian: 'Ce lo troviamo spesso in questa situazione.', german: 'Wir finden uns oft in dieser Situation wieder.' },
      { italian: 'Non me lo trovo spiegato bene.', german: 'Ich finde es nicht gut erklärt.' }
    ]
  },

  PENSARE: {
    name: 'PENSARE (denken)',
    sentences: [
      { italian: "Lo penso anch'io.", german: 'Das denke ich auch.' },
      { italian: 'Non lo penso possibile.', german: 'Ich halte es nicht für möglich.' },
      { italian: 'Te ne pensi qualcosa?', german: 'Was denkst du darüber?' },
      { italian: 'Ci sto pensando.', german: 'Ich denke darüber nach.' },
      { italian: 'Me lo pensavo diverso.', german: 'Ich hatte es mir anders vorgestellt.' },
      { italian: 'Non me ne penso capace.', german: 'Ich halte mich nicht dafür geeignet.' },
      { italian: 'Te lo pensi davvero?', german: 'Denkst du das wirklich?' },
      { italian: 'Non ci penso più.', german: 'Ich denke nicht mehr daran.' },
      { italian: 'Me ne penso spesso.', german: 'Ich denke oft daran.' },
      { italian: 'Te lo penso come soluzione.', german: 'Ich halte das für dich für eine Lösung.' },
      { italian: 'Non lo penso così grave.', german: 'Ich halte es nicht für so schlimm.' },
      { italian: 'Me lo sto pensando seriamente.', german: 'Ich überlege es mir ernsthaft.' },
      { italian: 'Non me ne penso responsabile.', german: 'Ich halte mich nicht dafür verantwortlich.' },
      { italian: 'Te ne pensi ancora?', german: 'Denkst du noch darüber nach?' },
      { italian: 'Me lo penso già fatto.', german: 'Ich sehe es gedanklich schon als erledigt.' }
    ]
  },

  PRENDERE: {
    name: 'PRENDERE (nehmen)',
    sentences: [
      { italian: 'Me lo prendo io.', german: 'Ich nehme es.' },
      { italian: 'Te lo prendi tu o io?', german: 'Nimmst du es oder soll ich?' },
      { italian: 'Me ne prendo uno.', german: 'Ich nehme mir eins.' },
      { italian: 'Ce lo prendiamo dopo.', german: 'Wir nehmen es später.' },
      { italian: 'Te lo prendo al volo.', german: 'Ich nehme es schnell für dich mit.' },
      { italian: 'Non me lo prendo sul serio.', german: 'Ich nehme es nicht ernst.' },
      { italian: 'Me la sono presa male.', german: 'Ich habe es übel genommen.' },
      { italian: 'Te la prendi sempre per tutto.', german: 'Du nimmst dir immer alles zu Herzen.' },
      { italian: 'Non me ne prendere.', german: 'Nimm es mir nicht übel.' },
      { italian: 'Me lo prendo come complimento.', german: 'Ich nehme es als Kompliment.' },
      { italian: 'Te lo prendi un caffè?', german: 'Nimmst du einen Kaffee?' },
      { italian: 'Ce ne prendiamo due.', german: 'Wir nehmen zwei davon.' },
      { italian: 'Me lo sono preso ieri.', german: 'Ich habe es mir gestern genommen.' },
      { italian: 'Non me lo prendere così.', german: 'Nimm es nicht so auf.' },
      { italian: 'Te lo prendi tu il conto?', german: 'Übernimmst du die Rechnung?' }
    ]
  },

  METTERE: {
    name: 'METTERE (legen/stellen)',
    sentences: [
      { italian: 'Lo metto io sul tavolo.', german: 'Ich lege es auf den Tisch.' },
      { italian: 'Me lo metti qui, per favore?', german: 'Legst du es mir bitte hierhin?' },
      { italian: 'Ce lo mettiamo dopo.', german: 'Wir legen es später hin.' },
      { italian: 'Non me lo mettere così.', german: 'Leg es mir nicht so hin.' },
      { italian: 'Te lo metto da parte.', german: 'Ich lege es dir beiseite.' },
      { italian: 'Me ne metti un po\' di più?', german: 'Tust du mir etwas mehr davon drauf?' },
      { italian: "Ce l'ho messo apposta.", german: 'Ich habe es absichtlich hingelegt.' },
      { italian: 'Non me lo sono messo bene.', german: 'Ich habe es mir nicht richtig angezogen.' },
      { italian: 'Te lo metto per iscritto.', german: 'Ich halte es dir schriftlich fest.' },
      { italian: 'Me la metto via.', german: 'Ich stecke es weg / ich vergesse es.' },
      { italian: 'Me lo metto nello zaino.', german: 'Ich packe es in den Rucksack.' },
      { italian: 'Me la sono messa via per dopo.', german: 'Ich habe es mir für später weggelegt.' },
      { italian: 'Non me lo mettere in testa.', german: 'Red dir das nicht ein.' },
      { italian: 'Me lo metto in calendario.', german: 'Ich trage es mir im Kalender ein.' }
    ]
  },

  TENERE: {
    name: 'TENERE (behalten/halten)',
    sentences: [
      { italian: 'Me lo tengo io.', german: 'Ich behalte es.' },
      { italian: 'Me lo tengo per sicurezza.', german: 'Ich behalte es zur Sicherheit.' },
      { italian: 'Te lo tieni tu?', german: 'Behältst du es?' },
      { italian: 'Te lo tieni ancora?', german: 'Behältst du es noch?' },
      { italian: 'Ce lo teniamo per dopo.', german: 'Wir behalten es für später.' },
      { italian: 'Non me lo tenere nascosto.', german: 'Behalt es mir nicht vor.' },
      { italian: 'Me ne tengo uno.', german: 'Ich behalte mir eins.' },
      { italian: 'Te lo tengo da parte.', german: 'Ich halte es dir zurück.' },
      { italian: 'Non me lo tengo dentro.', german: 'Ich behalte es nicht für mich.' },
      { italian: 'Ce la teniamo stretta.', german: 'Wir halten daran fest.' },
      { italian: 'Me lo sono tenuto fino ad oggi.', german: 'Ich habe es bis heute behalten.' },
      { italian: 'Te lo tieni per te.', german: 'Du behältst es für dich.' },
      { italian: 'Te lo tieni come riferimento.', german: 'Du behältst es als Referenz.' },
      { italian: 'Me ne tengo responsabile.', german: 'Ich übernehme die Verantwortung dafür.' }
    ]
  },

  LASCIARE: {
    name: 'LASCIARE (lassen)',
    sentences: [
      { italian: 'Lascialo stare.', german: 'Lass es gut sein.' },
      { italian: 'Me lo lasci dire.', german: 'Lass mich das sagen.' },
      { italian: 'Me lo lasci un attimo?', german: 'Lässt du es mir kurz da?' },
      { italian: 'Te lo lascio qui.', german: 'Ich lasse es dir hier.' },
      { italian: 'Ce lo lasciamo alle spalle.', german: 'Wir lassen es hinter uns.' },
      { italian: 'Non me lo lasciare così.', german: 'Lass es mir nicht so zurück.' },
      { italian: 'Te lo lascio scegliere.', german: 'Ich lasse dich entscheiden.' },
      { italian: 'Te ne lascio uno.', german: 'Ich lasse dir eins da.' },
      { italian: 'Me lo ha lasciato detto.', german: 'Er/Sie hat es mir ausrichten lassen.' },
      { italian: 'Non me ne lasciare fuori.', german: 'Lass mich da nicht außen vor.' },
      { italian: 'Te lo lascio fare.', german: 'Ich überlasse es dir.' },
      { italian: 'Ce lo siamo lasciati alle spalle.', german: 'Wir haben es hinter uns gelassen.' },
      { italian: 'Lascia perdere il resto.', german: 'Vergiss das Wechselgeld.' },
      { italian: 'Lo lasciamo sul tavolo.', german: 'Wir lassen es auf dem Tisch.' },
      { italian: 'Lasciami passare.', german: 'Lass mich vorbei.' }
    ]
  },

  ARRIVARE: {
    name: 'ARRIVARE (ankommen)',
    sentences: [
      { italian: 'Ci arrivo subito.', german: 'Ich komme gleich darauf / ich verstehe es gleich.' },
      { italian: 'Non ci arrivo.', german: 'Ich verstehe es nicht.' },
      { italian: 'Te lo faccio arrivare domani.', german: 'Ich lasse es dir morgen zukommen.' },
      { italian: 'Ce ne arrivano altri.', german: 'Weitere kommen bei uns an.' },
      { italian: 'Non me ne arriva nessuno.', german: 'Bei mir kommt nichts an.' },
      { italian: 'Te ne arriva uno più tardi.', german: 'Später kommt noch eins bei dir an.' },
      { italian: 'Ci siamo arrivati insieme.', german: 'Wir sind gemeinsam darauf gekommen.' },
      { italian: 'Non ci arrivo a fine mese.', german: 'Ich komme finanziell nicht bis Monatsende.' },
      { italian: 'Te lo faccio arrivare per email.', german: 'Ich lasse es dir per E-Mail zukommen.' },
      { italian: 'Non me lo fa arrivare.', german: 'Es erreicht mich nicht.' },
      { italian: 'Ci arrivo tra cinque minuti.', german: 'Ich bin in fünf Minuten da.' },
      { italian: 'È già arrivato?', german: 'Ist es schon angekommen?' },
      { italian: 'Mi è arrivato il messaggio.', german: 'Die Nachricht ist angekommen.' },
      { italian: 'Quando arrivi?', german: 'Wann kommst du an?' },
      { italian: 'Non mi è arrivato niente.', german: 'Bei mir ist nichts angekommen.' },
      { italian: 'Arriviamo insieme.', german: 'Wir kommen zusammen.' },
      { italian: 'Il conto è arrivato.', german: 'Die Rechnung ist da.' },
      { italian: 'Arriva tra poco.', german: 'Es kommt gleich.' },
      { italian: 'Ci arrivo, aspetta.', german: 'Ich verstehe, warte kurz.' },
      { italian: 'Ci arrivo piano piano.', german: 'Ich komme langsam dahinter.' },
      { italian: 'Non ci sono ancora arrivato.', german: 'Ich habe es noch nicht ganz verstanden.' },
      { italian: 'Te ne arriva notizia.', german: 'Du bekommst davon Nachricht.' },
      { italian: 'Ce ne arrivano poche.', german: 'Davon kommen nur wenige an.' },
      { italian: 'Non me ne è arrivata conferma.', german: 'Bei mir ist keine Bestätigung angekommen.' },
      { italian: 'Te lo faccio arrivare in giornata.', german: 'Ich lasse es dir heute noch zukommen.' },
      { italian: 'Ci siamo arrivati tardi.', german: 'Wir sind spät darauf gekommen.' },
      { italian: 'Non ci arrivo con i tempi.', german: 'Ich komme zeitlich nicht hin.' },
      { italian: 'Te ne arriva una copia.', german: 'Du bekommst eine Kopie davon.' },
      { italian: 'Ce lo facciamo arrivare.', german: 'Wir lassen es uns zukommen.' },
      { italian: 'Non me lo fa arrivare chiaro.', german: 'Es kommt bei mir nicht klar an.' },
      { italian: 'Non ci arrivo da solo.', german: 'Ich schaffe es allein nicht.' },
      { italian: 'Ce ne siamo arrivati insieme.', german: 'Wir sind gemeinsam dahin gekommen.' }
    ]
  },

  CREDERE: {
    name: 'CREDERE (glauben)',
    sentences: [
      { italian: 'Ci credo.', german: 'Ich glaube es.' },
      { italian: 'Non ci credo più.', german: 'Ich glaube nicht mehr daran.' },
      { italian: 'Te lo credo.', german: 'Ich glaube dir das.' },
      { italian: 'Non te lo credo.', german: 'Das glaube ich dir nicht.' },
      { italian: 'Me ne credo capace.', german: 'Ich halte mich dafür fähig.' },
      { italian: 'Non me ne credo responsabile.', german: 'Ich halte mich nicht dafür verantwortlich.' },
      { italian: 'Te ne credi sicuro?', german: 'Bist du dir dessen sicher?' },
      { italian: 'Ce lo crediamo possibile.', german: 'Wir halten es für möglich.' },
      { italian: 'Non ci crede nessuno.', german: 'Niemand glaubt daran.' },
      { italian: 'Te lo faccio credere.', german: 'Ich lasse dich das glauben.' },
      { italian: 'Ci credi davvero?', german: 'Glaubst du das wirklich?' },
      { italian: "Ci credo anch'io.", german: 'Das glaube ich auch.' },
      { italian: 'Voglio crederci.', german: 'Ich will daran glauben.' },
      { italian: 'Non ci credo tanto.', german: 'Ich glaube nicht so richtig daran.' },
      { italian: 'Ti voglio credere.', german: 'Ich möchte dir glauben.' }
    ]
  },

  PARLARE: {
    name: 'PARLARE (sprechen)',
    sentences: [
      { italian: 'Te ne parlo dopo.', german: 'Ich spreche später mit dir darüber.' },
      { italian: 'Non gliene parlare adesso.', german: 'Sprich jetzt nicht mit ihm/ihr darüber.' },
      { italian: 'Ce ne parliamo domani.', german: 'Wir sprechen morgen darüber.' },
      { italian: 'Me ne ha parlato ieri.', german: 'Er/Sie hat gestern mit mir darüber gesprochen.' },
      { italian: 'Non me ne parlare più.', german: 'Sprich mich nicht mehr darauf an.' },
      { italian: 'Te lo parlo chiaramente.', german: 'Ich sage es dir ganz offen.' },
      { italian: 'Ce ne parlano spesso.', german: 'Sie sprechen oft mit uns darüber.' },
      { italian: 'Non gliene ho mai parlato.', german: 'Ich habe nie mit ihm/ihr darüber gesprochen.' },
      { italian: 'Te ne parlo volentieri.', german: 'Ich spreche gern mit dir darüber.' },
      { italian: 'Me lo ha parlato male.', german: 'Er/Sie hat schlecht darüber gesprochen.' },
      { italian: 'Ne parliamo dopo.', german: 'Wir reden später darüber.' },
      { italian: 'Ne parliamo a cena.', german: 'Wir besprechen es beim Abendessen.' },
      { italian: 'Non parlarne adesso.', german: 'Sprich jetzt nicht darüber.' },
      { italian: 'Ne parlano tutti.', german: 'Alle reden darüber.' },
      { italian: 'Ne parliamo domani.', german: 'Wir reden morgen darüber.' },
      { italian: 'Parlane con lui.', german: 'Sprich mit ihm darüber.' },
      { italian: 'Non ne voglio parlare.', german: 'Ich will nicht darüber reden.' },
      { italian: 'Ne abbiamo parlato ieri.', german: 'Wir haben gestern darüber gesprochen.' },
      { italian: 'Te ne parlo un attimo.', german: 'Ich sage dir kurz was dazu.' }
    ]
  }
};
